#pragma once

#include <stdint.h>

typedef struct
{
    uint32_t len;
    uint32_t offset;
} cnfsFileEntry;

typedef enum
{
    FAIRY_FOUNTAIN_MID          = 0,
    FAUXRIO_KART_MID            = 1,
    FOLLINESQUE_MID             = 2,
    ARROW_10_WSG                = 3,
    ARROW_12_WSG                = 4,
    ARROW_18_WSG                = 5,
    ARROW_19_WSG                = 6,
    ARROW_21_WSG                = 7,
    ARROW_5_WSG                 = 8,
    ARROW_8_WSG                 = 9,
    ARROW_9_WSG                 = 10,
    BACKLIGHT_DISABLED_WSG      = 11,
    BACKLIGHT_ENABLED_WSG       = 12,
    BANANA_MID                  = 13,
    BASS_WSG                    = 14,
    BATT_1_WSG                  = 15,
    BATT_2_WSG                  = 16,
    BATT_3_WSG                  = 17,
    BATT_4_WSG                  = 18,
    BLOCK_1_MID                 = 19,
    BLOCK_2_MID                 = 20,
    BRASS_WSG                   = 21,
    BUTTON_A_WSG                = 22,
    BUTTON_B_WSG                = 23,
    BUTTON_MENU_WSG             = 24,
    BUTTON_PAUSE_WSG            = 25,
    BUTTON_SYSTEM_WSG           = 26,
    BUTTON_UP_WSG               = 27,
    CHANNELS_WSG                = 28,
    CHROMATIC_PERCUSSION_WSG    = 29,
    COLOSSUS_BIN                = 30,
    DEFAULT_SETTING_WSG         = 31,
    DONUT_FEST_BIN              = 32,
    DONUT_MAG_BIN               = 33,
    DOUBLE_QUAVER_WSG           = 34,
    EIGHTBIT_ATARI_GRUBE_2_FONT = 35,
    ENABLE_WSG                  = 36,
    ENSEMBLE_WSG                = 37,
    ETHNIC_WSG                  = 38,
    EXAMPLE_BG_WSG              = 39,
    F_CLEF_WSG                  = 40,
    FAST_FORWARD_WSG            = 41,
    FLAT_IBM_VGA_8_WSG          = 42,
    FLAT_LOGBOOK_WSG            = 43,
    GAMECUBE_MID                = 44,
    GMCC_MID                    = 45,
    GUITAR_WSG                  = 46,
    HALF_NOTE_WSG               = 47,
    HAMBURGER_WSG               = 48,
    HD_CREDITS_MID              = 49,
    HOTROD_MID                  = 50,
    IBM_VGA_8_FONT              = 51,
    IGNORE_WSG                  = 52,
    INTERFACE_WSG               = 53,
    INTRO_SWADGE_WSG            = 54,
    JUKEBOX_WSG                 = 55,
    KID_0_WSG                   = 56,
    KID_1_WSG                   = 57,
    LEDS_DISABLED_WSG           = 58,
    LEDS_ENABLED_WSG            = 59,
    LOGBOOK_FONT                = 60,
    LOOP_WSG                    = 61,
    MAGFEST_BIN                 = 62,
    MAGFEST_BANK_WSG            = 63,
    METRONOME_BOTTOM_WSG        = 64,
    METRONOME_TOP_WSG           = 65,
    MIDI_VOLUME_WSG             = 66,
    MUSIC_DISABLED_WSG          = 67,
    MUSIC_ENABLED_WSG           = 68,
    NORI_2_BIN                  = 69,
    ODE_MID                     = 70,
    OPEN_SONG_WSG               = 71,
    ORGAN_WSG                   = 72,
    PANGO_FW_FONT               = 73,
    PAUSE_WSG                   = 74,
    PERCUSSION_WSG              = 75,
    PERCUSSIVE_WSG              = 76,
    PIANO_WSG                   = 77,
    PIPE_WSG                    = 78,
    PITCH_WHEEL_WSG             = 79,
    PLAY_WSG                    = 80,
    PLAYER_WSG                  = 81,
    PLAYPAUSE_WSG               = 82,
    QUAVER_WSG                  = 83,
    RADIOSTARS_FONT             = 84,
    REED_WSG                    = 85,
    RESET_WSG                   = 86,
    RETRO_LOGO_FONT             = 87,
    RIGHTEOUS_150_FONT          = 88,
    RODIN_EB_FONT               = 89,
    SECRET_MID                  = 90,
    SEQ_DRUMS_WSG               = 91,
    SEQ_EIGHTH_NOTE_WSG         = 92,
    SEQ_GUITAR_WSG              = 93,
    SEQ_HALF_NOTE_WSG           = 94,
    SEQ_PIANO_WSG               = 95,
    SEQ_QUARTER_NOTE_WSG        = 96,
    SEQ_SAX_WSG                 = 97,
    SEQ_SIXTEENTH_NOTE_WSG      = 98,
    SEQ_SYNTH_WSG               = 99,
    SEQ_TRUMPET_WSG             = 100,
    SEQ_WHOLE_NOTE_WSG          = 101,
    SEVEN_SEGMENT_FONT          = 102,
    SFX_DISABLED_WSG            = 103,
    SFX_ENABLED_WSG             = 104,
    SHUFFLE_WSG                 = 105,
    SKIP_WSG                    = 106,
    SOLO_STRINGS_WSG            = 107,
    SONIC_FONT                  = 108,
    SOUND_EFFECTS_WSG           = 109,
    SPK_WSG                     = 110,
    STEREO_MID                  = 111,
    STEREO_TEST_MID             = 112,
    STOP_WSG                    = 113,
    SYNTH_EFFECTS_WSG           = 114,
    SYNTH_LEAD_WSG              = 115,
    SYNTH_PAD_WSG               = 116,
    TAILLESS_QUAVER_WSG         = 117,
    TINY_NUMBERS_FONT           = 118,
    TOUCH_GEM_WSG               = 119,
    TOUCHPAD_WSG                = 120,
    TOUCHPAD_JOYSTICK_WSG       = 121,
    TOUCHPAD_SPIN_WSG           = 122,
    TREBLE_CLEF_WSG             = 123,
    TWO_TAIL_QUAVER_WSG         = 124,
    USB_WSG                     = 125,
    USB_MODE_WSG                = 126,
    VIEW_MODE_WSG               = 127,
    WHOLE_NOTE_WSG              = 128,
    WILHELM_BIN                 = 129,
    WOOD_BACKGROUND_WSG         = 130,
    YALIKEJAZZ_MID              = 131,
    CNFS_NUM_FILES              = 132,
} cnfsFileIdx_t;

const uint8_t* getCnfsImage(void);
int32_t getCnfsSize(void);
const cnfsFileEntry* getCnfsFiles(void);
int32_t getCnfsNumFiles(void);
