//==============================================================================
// Include
//==============================================================================

#include "ci_upgrades.h"

//==============================================================================
// Consts
//==============================================================================

const ciUpgrade_t upgradeList[] = {
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Branches",
        .desc = "A nice bundle of sticks to lie on. It's surprisingly comfortable!",
        .type = CI_BED,
        .rank = 1,
        .items[0].item = CI_STICK,
        .items[0].qty = 20,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 2,
    },
    {
        .title = "Straw Matteress",
        .desc = "It finally feels like a real bed",
        .type = CI_BED,
        .rank = 2,
        .items[0].item = CI_DRIED_GRASS,
        .items[0].qty = 30,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 3,
    },
    {
        .title = "Pelt Blanket",
        .desc = "Finally, something to keep the heat in",
        .type = CI_BED,
        .rank = 3,
        .items[0].item = CI_HIDE,
        .items[0].qty = 15,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 4,
    },
    {
        .title = "Cloth Blanket",
        .desc = "A cloth blanket seems like the height of luxury out here",
        .type = CI_BED,
        .rank = 4,
        .items[0].item = CI_CLOTH,
        .items[0].qty = 20,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 5,
    },
    {
        .title = "Enchanted Blanket",
        .desc = "Magical blanket that keeps you at the perfect temperature",
        .type = CI_BED,
        .rank = 5,
        .items[0].item = CI_CLOTH,
        .items[0].qty = 20,
        .items[1].item = CI_POLISHED_CRYSTAL,
        .items[1].qty = 5,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 6,
    },
    {
        .title = "Arms",
        .desc = "Why can't you hold all these limes?",
        .type = CI_HAULING,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 50,
    },
    {
        .title = "Pouch",
        .desc = "Hard ground that isn't very restful",
        .type = CI_HAULING,
        .rank = 1,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 70,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_HAULING,
        .rank = 2,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 100,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_HAULING,
        .rank = 3,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 150,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_HAULING,
        .rank = 4,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 250,
    },
    {
        .title = "Golem",
        .desc = "Work smarter, not harder",
        .type = CI_HAULING,
        .rank = 5,
        .items[0].item = CI_POLISHED_ROCK,
        .items[0].qty = 20,
        .items[1].item = CI_POLISHED_CRYSTAL,
        .items[1].qty = 15,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 400,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
    {
        .title = "Ground",
        .desc = "Hard ground that isn't very restful",
        .type = CI_BED,
        .rank = 0,
        .items[0].item = CI_NO_ITEM,
        .items[0].qty = 0,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty = 0,
        .items[2].item = CI_NO_ITEM,
        .items[2].qty = 0,
        .requiredItem.item = CI_NO_ITEM,
        .requiredItem.qty = 0,
        .foodReq = 0,
        .effect = 1,
    },
};