#ifndef PLATFORMER_COMMON_TYPEDEF_INCLUDED
#define PLATFORMER_COMMON_TYPEDEF_INCLUDED

#include "cnfs.h"
#include "vector2d.h"
#include "mgLeveldef.h"
#include "palette.h"
#include "trophy.h"

//==============================================================================
// Constants
//==============================================================================

#define SUBPIXEL_RESOLUTION                 4
#define MG_TILESIZE_IN_POWERS_OF_2          4
#define MG_TILESIZE                         16
#define MG_HALF_TILESIZE                    8
#define DESPAWN_THRESHOLD                   64
#define MG_PLAYER_LIFEBAR_Y_BOTTOM_LOCATION 148

static const cnfsFileIdx_t MG_BGMS[]
    = {BGM_DEADEYE_CHIRPZI_MID,    BGM_BOSS_DEADEYE_CHIRPZI_MID, BGM_DRAIN_BAT_MID,
       BGM_BOSS_DRAIN_BAT_MID,     BGM_FLARE_GRYFFYN_MID,        BGM_BOSS_FLARE_GRIFFIN_MID,
       BGM_GRIND_PANGOLIN_MID,     BGM_BOSS_GRIND_PANGOLIN_MID,  BGM_KINETIC_DONUT_MID,
       BGM_BOSS_KINETIC_DONUT_MID, BGM_RIP_BARONESS_MID,         BGM_BOSS_HANK_WADDLE_MID,
       BGM_SEVER_YAGATA_MID,       BGM_BOSS_SEVER_YAGATA_MID,    BGM_SMASH_GORILLA_MID,
       BGM_BOSS_SMASH_GORILLA_MID, BGM_BOSS_TRASH_MAN_MID,       BGM_BIGMA_MID,
       BGM_BOSS_BIGMA_MID,         BGM_STAGE_SELECT_MID,         BGM_NAME_ENTRY_MID};

//==============================================================================
// Macros
//==============================================================================

#define SIGNOF(x)             ((x > 0) - (x < 0))
#define MG_TO_TILECOORDS(x)   ((x) >> MG_TILESIZE_IN_POWERS_OF_2)
#define TO_PIXEL_COORDS(x)    ((x) >> SUBPIXEL_RESOLUTION)
#define TO_SUBPIXEL_COORDS(x) ((x) << SUBPIXEL_RESOLUTION)

typedef struct platformer_t platformer_t;
typedef struct mgEntityManager_t mgEntityManager_t;
typedef struct mgTilemap_t mgTilemap_t;
typedef struct mgEntity_t mgEntity_t;
typedef struct mgEntitySpawnData_t mgEntitySpawnData_t;

typedef struct
{
    int32_t size;
    vec_t collisionPoints[];
} mg_EntityTileCollisionPointList_t;

typedef struct
{
    const mg_EntityTileCollisionPointList_t* bottomEdge;
    const mg_EntityTileCollisionPointList_t* topEdge;
    const mg_EntityTileCollisionPointList_t* rightEdge;
    const mg_EntityTileCollisionPointList_t* leftEdge;
} mg_EntityTileCollider_t;

typedef enum
{
    MG_ST_NULL,
    MG_ST_TITLE_SCREEN,
    MG_ST_READY_SCREEN,
    MG_ST_GAME,
    MG_ST_DEAD,
    MG_ST_LEVEL_CLEAR,
    MG_ST_WORLD_CLEAR,
    MG_ST_GAME_CLEAR,
    MG_ST_GAME_OVER,
    MG_ST_HIGH_SCORE_ENTRY,
    MG_ST_HIGH_SCORE_TABLE,
    MG_ST_PAUSE,
    MG_ST_CUTSCENE,
} mg_gameStateEnum_t;

typedef enum
{
    MG_BGM_NO_CHANGE = -1,
    MG_BGM_NULL,
    MG_BGM_DEADEYE_CHIRPZI,
    MG_BGM_BOSS_DEADEYE_CHIRPZI,
    MG_BGM_DRAIN_BAT,
    MG_BGM_BOSS_DRAIN_BAT,
    MG_BGM_FLARE_GRYFFYN,
    MG_BGM_BOSS_FLARE_GRYFFYN,
    MG_BGM_GRIND_PANGOLIN,
    MG_BGM_BOSS_GRIND_PANGOLIN,
    MG_BGM_KINETIC_DONUT,
    MG_BGM_BOSS_KINETIC_DONUT,
    MG_BGM_RIP_BARONESS,
    MG_BGM_BOSS_HANK_WADDLE,
    MG_BGM_SEVER_YAGATA,
    MG_BGM_BOSS_SEVER_YAGATA,
    MG_BGM_SMASH_GORILLA,
    MG_BGM_BOSS_SMASH_GORILLA,
    MG_BGM_BOSS_TRASH_MAN,
    MG_BGM_BIGMA,
    MG_BGM_BOSS_BIGMA,
    MG_BGM_LEVEL_CLEAR_JINGLE,
    MG_BGM_POST_FIGHT,
    MG_BGM_PRE_FIGHT,
    MG_BGM_STAGE_SELECT,
    MG_BGM_NAME_ENTRY
} mg_bgmEnum_t;

typedef enum
{
    MG_SP_PLAYER_IDLE,
    MG_SP_PLAYER_WALK1,
    MG_SP_PLAYER_WALK2,
    MG_SP_PLAYER_WALK3,
    MG_SP_PLAYER_WALK4,
    MG_SP_PLAYER_WALK5,
    MG_SP_PLAYER_WALK6,
    MG_SP_PLAYER_WALK7,
    MG_SP_PLAYER_WALK8,
    MG_SP_PLAYER_WALK9,
    MG_SP_PLAYER_WALK10,
    MG_SP_PLAYER_JUMP,
    MG_SP_PLAYER_JUMP1,
    MG_SP_PLAYER_JUMP2,
    MG_SP_PLAYER_JUMP3,
    MG_SP_PLAYER_JUMP4,
    MG_SP_PLAYER_SLIDE,
    MG_SP_PLAYER_DASH_SLIDE,
    MG_SP_PLAYER_HURT,
    MG_SP_PLAYER_CLIMB,
    MG_SP_PLAYER_WIN,
    MG_SP_ENEMY_BASIC,
    MG_SP_HITBLOCK_CONTAINER,
    MG_SP_HITBLOCK_BRICKS,
    MG_SP_DUSTBUNNY_IDLE,
    MG_SP_DUSTBUNNY_CHARGE,
    MG_SP_DUSTBUNNY_JUMP,
    MG_SP_GAMING_1,
    MG_SP_GAMING_2,
    MG_SP_GAMING_3,
    MG_SP_MUSIC_1,
    MG_SP_MUSIC_2,
    MG_SP_MUSIC_3,
    MG_SP_WARP_1,
    MG_SP_WARP_2,
    MG_SP_WARP_3,
    MG_SP_WASP_1,
    MG_SP_WASP_2,
    MG_SP_WASP_DIVE,
    MG_SP_1UP_1,
    MG_SP_1UP_2,
    MG_SP_1UP_3,
    MG_SP_WAVEBALL_1,
    MG_SP_WAVEBALL_2,
    MG_SP_WAVEBALL_3,
    MG_SP_ENEMY_BUSH_L2,
    MG_SP_ENEMY_BUSH_L3,
    MG_SP_DUSTBUNNY_L2_IDLE,
    MG_SP_DUSTBUNNY_L2_CHARGE,
    MG_SP_DUSTBUNNY_L2_JUMP,
    MG_SP_DUSTBUNNY_L3_IDLE,
    MG_SP_DUSTBUNNY_L3_CHARGE,
    MG_SP_DUSTBUNNY_L3_JUMP,
    MG_SP_WASP_L2_1,
    MG_SP_WASP_L2_2,
    MG_SP_WASP_L2_DIVE,
    MG_SP_WASP_L3_1,
    MG_SP_WASP_L3_2,
    MG_SP_WASP_L3_DIVE,
    MG_SP_CHECKPOINT_INACTIVE,
    MG_SP_CHECKPOINT_ACTIVE_1,
    MG_SP_CHECKPOINT_ACTIVE_2,
    MG_SP_BOUNCE_BLOCK,
    MG_SP_INVISIBLE_WARP_WALL,
    MG_SP_INVISIBLE_WARP_FLOOR,
    MG_SP_SPIKY_MCGEE_2,
    MG_SP_CHARGIN_SCHMUCK_RUN1,
    MG_SP_CHARGIN_SCHMUCK_RUN2,
    MG_SP_TURRET_HORIZONTAL,
    MG_SP_TURRET_45DEG,
    MG_SP_TURRET_VERTICAL,
    MG_SP_LEMON_SHOT,
    MG_SP_SHELDON_SHIELDY_SHIELD,
    MG_SP_SHELDON_SHIELDY_WALK1,
    MG_SP_SHELDON_SHIELDY_WALK2,
    MG_SP_SHELDON_SHIELDY_WALK3,
    MG_SP_SPIKY_MCGEE,
    MG_SP_AIR_TURRET,
    MG_SP_BOUNCE_PAD,
    MG_SP_BOUNCE_PAD_DIAGONAL,
    MG_SP_MIXTAPE,
    MG_SP_BOSS_DOOR,
    MG_SP_PLAYER_HURT_2,
    MG_SP_PLAYER_HURT_3,
    MG_SP_PLAYER_MIC_DROP_1,
    MG_SP_PLAYER_MIC_DROP_2,
    MG_SP_CRAWLER_TOP,
    MG_SP_CRAWLER_RIGHT,
    MG_SP_CRAWLER_BOTTOM,
    MG_SP_CRAWLER_LEFT,
    MG_SP_PLAYER_SUREYOUCAN_1,
    MG_SP_PLAYER_SUREYOUCAN_2,
    MG_SP_CRUMBLED_BLOCK,
    MG_SP_CHARGE_SHOT_LVL1_1,
    MG_SP_CHARGE_SHOT_LVL1_2,
    MG_SP_CHARGE_SHOT_LVL1_3,
    MG_SP_CHARGE_SHOT_MAX_1,
    MG_SP_CHARGE_SHOT_MAX_2,
    MG_SP_CHARGE_SHOT_MAX_3,
    MG_SP_BOSS_0,
    MG_SP_BOSS_1,
    MG_SP_BOSS_2,
    MG_SP_BOSS_3,
    MG_SP_BOSS_4,
    MG_SP_BOSS_5,
    MG_SP_BOSS_6,
    MG_SP_BOSS_7,
} mg_spriteDef_t;

typedef enum
{
    MG_TILE_EMPTY,
    MG_TILE_WARP_0,
    MG_TILE_WARP_1,
    MG_TILE_WARP_2,
    MG_TILE_WARP_3,
    MG_TILE_WARP_4,
    MG_TILE_WARP_5,
    MG_TILE_WARP_6,
    MG_TILE_WARP_7,
    MG_TILE_WARP_8,
    MG_TILE_WARP_9,
    MG_TILE_WARP_A,
    MG_TILE_WARP_B,
    MG_TILE_WARP_C,
    MG_TILE_WARP_D,
    MG_TILE_WARP_E,
    MG_TILE_WARP_F,
    MG_TILE_CTNR_COIN,
    MG_TILE_CTNR_10COIN,
    MG_TILE_CTNR_POW1,
    MG_TILE_CTNR_POW2,
    MG_TILE_CTNR_LADDER,
    MG_TILE_CTNR_1UP,
    MG_TILE_CTRL_LEFT,
    MG_TILE_CTRL_RIGHT,
    MG_TILE_CTRL_UP,
    MG_TILE_CTRL_DOWN,
    MG_TILE_UNUSED_27,
    MG_TILE_UNUSED_28,
    MG_TILE_UNUSED_29,
    MG_TILE_INVISIBLE_BLOCK,
    MG_TILE_INVISIBLE_CONTAINER,
    MG_TILE_GRASS,
    MG_TILE_GROUND,
    MG_TILE_BLOCK,
    MG_TILE_METAL_BLOCK,
    MG_TILE_METAL_PIPE_H,
    MG_TILE_METAL_PIPE_V,
    MG_TILE_DIRT_PATH,
    MG_TILEGIRDER,
    MG_TILE_SOLID_UNUSED_42,
    MG_TILE_SOLID_UNUSED_43,
    MG_TILE_SOLID_UNUSED_44,
    MG_TILE_SOLID_UNUSED_45,
    MG_TILE_SOLID_UNUSED_46,
    MG_TILE_SOLID_UNUSED_47,
    MG_TILE_SOLID_UNUSED_48,
    MG_TILE_SOLID_UNUSED_49,
    MG_TILE_SOLID_UNUSED_50,
    MG_TILE_SOLID_UNUSED_51,
    MG_TILE_SOLID_UNUSED_52,
    MG_TILE_SOLID_UNUSED_53,
    MG_TILE_SOLID_UNUSED_54,
    MG_TILE_SOLID_UNUSED_55,
    MG_TILE_SOLID_UNUSED_56,
    MG_TILE_SOLID_UNUSED_57,
    MG_TILE_SOLID_UNUSED_58,
    MG_TILE_GOAL_100PTS = 128,
    MG_TILE_GOAL_500PTS,
    MG_TILE_GOAL_1000PTS,
    MG_TILE_GOAL_2000PTS,
    MG_TILE_GOAL_5000PTS,
    MG_TILE_CONTAINER_1,
    MG_TILE_CONTAINER_2,
    MG_TILE_CONTAINER_3,
    MG_TILE_BOUNCE_BLOCK_OLD,
    MG_TILE_COIN_1,
    MG_TILE_COIN_2,
    MG_TILE_COIN_3,
    MG_TILE_LADDER,
    MG_TILE_NONSOLID_INTERACTIVE_VISIBLE_71,
    MG_TILE_NONSOLID_INTERACTIVE_VISIBLE_72,
    MG_TILE_NONSOLID_INTERACTIVE_VISIBLE_73,
    MG_TILE_NONSOLID_INTERACTIVE_VISIBLE_74,
    MG_TILE_NONSOLID_INTERACTIVE_VISIBLE_75,
    MG_TILE_NONSOLID_INTERACTIVE_VISIBLE_76,
    MG_TILE_NONSOLID_INTERACTIVE_VISIBLE_77,
    MG_TILE_NONSOLID_INTERACTIVE_VISIBLE_78,
    MG_TILE_NONSOLID_INTERACTIVE_VISIBLE_79,
    MG_TILE_BG_GOAL_ZONE,
    MG_TILE_BG_ARROW_L,
    MG_TILE_BG_ARROW_R,
    MG_TILE_BG_ARROW_U,
    MG_TILE_BG_ARROW_D,
    MG_TILE_BG_ARROW_LU,
    MG_TILE_BG_ARROW_RU,
    MG_TILE_BG_ARROW_LD,
    MG_TILE_BG_ARROW_RD,
    MG_TILE_BG_CLOUD_LD,
    MG_TILE_BOUNCE_BLOCK,
    MG_TILE_BG_CLOUD_RD,
    MG_TILE_BG_CLOUD_LU,
    MG_TILE_BG_CLOUD_RU,
    MG_TILE_BG_CLOUD_D,
    MG_TILE_BG_CLOUD,
    MG_TILE_BRICK_BLOCK,
    MG_TILE_BG_MOUNTAIN_L,
    MG_TILE_BG_MOUNTAIN_U,
    MG_TILE_BG_MOUNTAIN_R,
    MG_TILE_BG_MOUNTAIN,
    MG_TILE_BG_METAL,
    MG_TILE_BG_CHAINS,
    MG_TILE_BG_WALL
} mg_tileIndex_t;

typedef enum
{
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_20 = 32,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_21,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_22,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_23,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_24,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_25,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_26,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_27,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_28,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_29,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2A,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2B,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2C,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2D,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2E,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2F,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_30,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_31,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_32,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_33,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_34,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_35,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_36,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_37,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_38,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_39,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3A,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3B,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3C,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3D,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3E,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3F,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_40,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_41,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_42,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_43,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_44,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_45,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_46,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_47,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_48,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_49,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4A,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4B,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4C,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4D,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4E,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4F,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_50,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_51,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_52,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_53,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_54,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_55,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_56,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_57,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_58,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_59,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5A,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5B,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5C,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5D,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5E,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5F,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_60,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_61,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_62,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_63,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_64,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_65,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_66,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_67,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_68,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_69,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6A,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6B,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6C,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6D,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6E,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6F,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_70,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_71,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_72,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_73,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_74,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_75,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_76,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_77,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_78,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_79,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_7A,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_7B,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_7C,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_7D,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_7E,
    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_7F,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_80, // Container Block
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_81, // Brick/Crumbling Block
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_82,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_83,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_84,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_85,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_86,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_87,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_88,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_89,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_8A,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_8B,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_8C,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_8D,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_8E,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_8F,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_90,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_91,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_92,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_93,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_94,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_95,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_96,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_97,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_98,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_99,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_9A,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_9B,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_9C,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_9D,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_9E,
    MG_TILE_SOLID_VISIBLE_INTERACTIVE_9F,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A0, // Ladder/chain
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A1, // Bounce Block
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A2, // Spikes/lava top
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A3, // Spikes/lava left
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A4, // Spikes/lava bottom
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A5, // Spikes/lava right
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A6, // Crumble block
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A7,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A8,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A9,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_AA,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_AB,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_AC,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_AD,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_AE,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_AF,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B0,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B1,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B2,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B3,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B4,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B5,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B6,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B7,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B8,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B9,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_BA,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_BB,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_BC,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_BD,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_BE,
    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_BF,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C0,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C1,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C2,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C3,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C4,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C5,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C6,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C7,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C8,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C9,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_CA,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_CB,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_CC,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_CD,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_CE,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_CF,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D0,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D1,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D2,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D3,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D4,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D5,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D6,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D7,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D8,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D9,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_DA,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_DB,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_DC,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_DD,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_DE,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_DF,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E0,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E1,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E2,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E3,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E4,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E5,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E6,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E7,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E8,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E9,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_EA,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_EB,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_EC,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_ED,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_EE,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_EF,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F0,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F1,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F2,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F3,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F4,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F5,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F6,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F7,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F8,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F9,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_FA,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_FB,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_FC,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_FD,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_FE,
    MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_FF
} mg_genericTileIndex_t;

typedef enum
{
    MG_WSG_PLAYER_IDLE,
    MG_WSG_PLAYER_WALK1,
    MG_WSG_PLAYER_WALK2,
    MG_WSG_PLAYER_WALK3,
    MG_WSG_PLAYER_WALK4,
    MG_WSG_PLAYER_WALK5,
    MG_WSG_PLAYER_WALK6,
    MG_WSG_PLAYER_WALK7,
    MG_WSG_PLAYER_WALK8,
    MG_WSG_PLAYER_WALK9,
    MG_WSG_PLAYER_WALK10,
    MG_WSG_PLAYER_JUMP,
    MG_WSG_PLAYER_JUMP1,
    MG_WSG_PLAYER_JUMP2,
    MG_WSG_PLAYER_JUMP3,
    MG_WSG_PLAYER_JUMP4,

    MG_WSG_PLAYER_SHOOT_IDLE,
    MG_WSG_PLAYER_SHOOT_WALK1,
    MG_WSG_PLAYER_SHOOT_WALK2,
    MG_WSG_PLAYER_SHOOT_WALK3,
    MG_WSG_PLAYER_SHOOT_WALK4,
    MG_WSG_PLAYER_SHOOT_WALK5,
    MG_WSG_PLAYER_SHOOT_WALK6,
    MG_WSG_PLAYER_SHOOT_WALK7,
    MG_WSG_PLAYER_SHOOT_WALK8,
    MG_WSG_PLAYER_SHOOT_WALK9,
    MG_WSG_PLAYER_SHOOT_WALK10,
    MG_WSG_PLAYER_SHOOT_JUMP,
    MG_WSG_PLAYER_SHOOT_JUMP1,
    MG_WSG_PLAYER_SHOOT_JUMP2,
    MG_WSG_PLAYER_SHOOT_JUMP3,
    MG_WSG_PLAYER_SHOOT_JUMP4,

    MG_WSG_PLAYER_SLIDE,
    MG_WSG_PLAYER_HURT,
    MG_WSG_PLAYER_CLIMB,
    MG_WSG_PLAYER_WIN,
    MG_WSG_ENEMY_BASIC,
    MG_WSG_DUSTBUNNY_IDLE,
    MG_WSG_DUSTBUNNY_CHARGE,
    MG_WSG_DUSTBUNNY_JUMP,
    MG_WSG_GAMING_1,
    MG_WSG_GAMING_2,
    MG_WSG_GAMING_3,
    MG_WSG_MUSIC_1,
    MG_WSG_MUSIC_2,
    MG_WSG_MUSIC_3,
    MG_WSG_WARP_1,
    MG_WSG_WARP_2,
    MG_WSG_WARP_3,
    MG_WSG_WASP_1,
    MG_WSG_WASP_2,
    MG_WSG_WASP_DIVE,
    MG_WSG_1UP_1,
    MG_WSG_1UP_2,
    MG_WSG_1UP_3,
    MG_WSG_WAVEBALL_1,
    MG_WSG_WAVEBALL_2,
    MG_WSG_WAVEBALL_3,
    MG_WSG_ENEMY_BUSH_L2,
    MG_WSG_ENEMY_BUSH_L3,
    MG_WSG_DUSTBUNNY_L2_IDLE,
    MG_WSG_DUSTBUNNY_L2_CHARGE,
    MG_WSG_DUSTBUNNY_L2_JUMP,
    MG_WSG_DUSTBUNNY_L3_IDLE,
    MG_WSG_DUSTBUNNY_L3_CHARGE,
    MG_WSG_DUSTBUNNY_L3_JUMP,
    MG_WSG_WASP_L2_1,
    MG_WSG_WASP_L2_2,
    MG_WSG_WASP_L2_DIVE,
    MG_WSG_WASP_L3_1,
    MG_WSG_WASP_L3_2,
    MG_WSG_WASP_L3_DIVE,
    MG_WSG_CHECKPOINT_INACTIVE,
    MG_WSG_CHECKPOINT_ACTIVE_1,
    MG_WSG_CHECKPOINT_ACTIVE_2,

    MG_WSG_GRASS,
    MG_WSG_GROUND,
    MG_WSG_BRICK_BLOCK,
    MG_WSG_BLOCK,
    MG_WSG_METAL_BLOCK,
    MG_WSG_METAL_PIPE_H,
    MG_WSG_METAL_PIPE_V,
    MG_WSG_BOUNCE_BLOCK,
    MG_WSG_DIRT_PATH,
    MG_WSG_GIRDER,
    MG_WSG_GOAL_100PTS,
    MG_WSG_GOAL_500PTS,
    MG_WSG_GOAL_1000PTS,
    MG_WSG_GOAL_2000PTS,
    MG_WSG_GOAL_5000PTS,
    MG_WSG_CONTAINER_1,
    MG_WSG_CONTAINER_2,
    MG_WSG_CONTAINER_3,
    MG_WSG_COIN_1,
    MG_WSG_COIN_2,
    MG_WSG_COIN_3,
    MG_WSG_LADDER,
    MG_WSG_BG_GOAL_ZONE,
    MG_WSG_BG_ARROW_L,
    MG_WSG_BG_ARROW_R,
    MG_WSG_BG_ARROW_U,
    MG_WSG_BG_ARROW_D,
    MG_WSG_BG_ARROW_LU,
    MG_WSG_BG_ARROW_RU,
    MG_WSG_BG_ARROW_LD,
    MG_WSG_BG_ARROW_RD,
    MG_WSG_BG_CLOUD_LD,
    MG_WSG_BG_CLOUD_M,
    MG_WSG_BG_CLOUD_RD,
    MG_WSG_BG_CLOUD_LU,
    MG_WSG_BG_CLOUD_RU,
    MG_WSG_BG_CLOUD_D,
    MG_WSG_BG_CLOUD,
    MG_WSG_BG_TALL_GRASS,
    MG_WSG_BG_MOUNTAIN_L,
    MG_WSG_BG_MOUNTAIN_U,
    MG_WSG_BG_MOUNTAIN_R,
    MG_WSG_BG_MOUNTAIN,
    MG_WSG_BG_METAL,
    MG_WSG_BG_CHAINS,
    MG_WSG_BG_WALL,

    MG_WSG_HP_BOTTOM_ALPHA = 299,
    MG_WSG_HP_MIDDLE_0,
    MG_WSG_HP_MIDDLE_1,
    MG_WSG_HP_MIDDLE_2,
    MG_WSG_HP_MIDDLE_3,
    MG_WSG_HP_MIDDLE_4,
    MG_WSG_HP_MIDDLE_5,
    MG_WSG_HP_MIDDLE_6,
    MG_WSG_HP_TOP_0,
    MG_WSG_HP_TOP_1,
    MG_WSG_HP_TOP_2,
    MG_WSG_HP_TOP_3,
    MG_WSG_HP_TOP_4,
    MG_WSG_HP_TOP_5,
    MG_WSG_HP_TOP_6,
    MG_WSG_HP_BOTTOM_BIGMA,
    MG_WSG_HP_BOSS_MIDDLE_0,
    MG_WSG_HP_BOSS_MIDDLE_1,
    MG_WSG_HP_BOSS_MIDDLE_2,
    MG_WSG_HP_BOSS_MIDDLE_3,
    MG_WSG_HP_BOSS_MIDDLE_4,
    MG_WSG_HP_BOSS_MIDDLE_5,
    MG_WSG_HP_BOSS_MIDDLE_6,
    MG_WSG_HP_BOSS_TOP_0,
    MG_WSG_HP_BOSS_TOP_1,
    MG_WSG_HP_BOSS_TOP_2,
    MG_WSG_HP_BOSS_TOP_3,
    MG_WSG_HP_BOSS_TOP_4,
    MG_WSG_HP_BOSS_TOP_5,
    MG_WSG_HP_BOSS_TOP_6,
    MG_WSG_SPIKY_MCGEE_2,
    MG_WSG_CHARGIN_SCHMUCK_RUN1,
    MG_WSG_CHARGIN_SCHMUCK_RUN2,
    MG_WSG_TURRET_HORIZONTAL,
    MG_WSG_TURRET_45DEG,
    MG_WSG_TURRET_VERTICAL,
    MG_WSG_LEMON_SHOT,
    MG_WSG_SHELDON_SHIELDY_SHIELD,
    MG_WSG_SHELDON_SHIELDY_WALK1,
    MG_WSG_SHELDON_SHIELDY_WALK2,
    MG_WSG_SHELDON_SHIELDY_WALK3,
    MG_WSG_SPIKY_MCGEE,
    MG_WSG_AIR_TURRET,
    MG_WSG_BOUNCE_PAD,
    MG_WSG_BOUNCE_PAD_DIAGONAL,
    MG_WSG_MIXTAPE,
    MG_WSG_BOSS_IDLE,
    MG_WSG_BOSS_MOVE_1,
    MG_WSG_BOSS_MOVE_2,
    MG_WSG_BOSS_MOVE_3,
    MG_WSG_BOSS_DOOR,
    MG_WSG_PLAYER_DASH_SLIDE,
    MG_WSG_PLAYER_HURT_2,
    MG_WSG_PLAYER_HURT_3,
    MG_WSG_PLAYER_MIC_DROP_1,
    MG_WSG_PLAYER_MIC_DROP_2,
    MG_WSG_PLAYER_SHIELD_1,
    MG_WSG_PLAYER_SHIELD_2,
    MG_WSG_PLAYER_SHIELD_3,
    MG_WSG_PLAYER_SHIELD_4,
    MG_WSG_PLAYER_SUREYOUCAN_1,
    MG_WSG_PLAYER_SUREYOUCAN_2,
    MG_WSG_CRUMBLED_BLOCK,
    MG_WSG_SALSA,
    MG_WSG_CHARGE_SHOT_LVL1_1,
    MG_WSG_CHARGE_SHOT_LVL1_2,
    MG_WSG_CHARGE_SHOT_LVL1_3,
    MG_WSG_CHARGE_SHOT_MAX_1,
    MG_WSG_CHARGE_SHOT_MAX_2,
    MG_WSG_CHARGE_SHOT_MAX_3
} mg_wsgIndex_t;

typedef enum
{
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_20 = 75,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_21,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_22,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_23,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_24,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_25,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_26,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_27,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_28,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_29,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2A,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2B,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2C,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2D,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2E,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2F,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_30,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_31,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_32,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_33,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_34,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_35,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_36,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_37,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_38,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_39,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3A,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3B,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3C,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3D,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3E,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3F,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_40,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_41,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_42,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_43,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_44,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_45,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_46,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_47,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_48,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_49,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4A,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4B,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4C,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4D,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4E,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4F,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_50,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_51,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_52,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_53,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_54,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_55,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_56,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_57,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_58,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_59,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5A,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5B,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5C,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5D,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5E,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5F,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_60,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_61,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_62,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_63,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_64,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_65,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_66,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_67,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_68,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_69,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6A,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6B,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6C,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6D,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6E,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6F,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_70,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_71,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_72,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_73,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_74,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_75,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_76,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_77,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_78,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_79,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_7A,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_7B,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_7C,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_7D,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_7E,
    MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_7F,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_80,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_81,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_82,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_83,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_84,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_85,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_86,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_87,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_88,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_89,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_8A,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_8B,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_8C,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_8D,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_8E,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_8F,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_90,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_91,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_92,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_93,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_94,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_95,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_96,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_97,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_98,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_99,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_9A,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_9B,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_9C,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_9D,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_9E,
    MG_WSG_TILE_SOLID_VISIBLE_INTERACTIVE_9F,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A0,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A1,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A2,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A3,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A4,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A5,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A6,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A7,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A8,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A9,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_AA,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_AB,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_AC,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_AD,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_AE,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_AF,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B0,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B1,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B2,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B3,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B4,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B5,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B6,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B7,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B8,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_B9,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_BA,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_BB,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_BC,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_BD,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_BE,
    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_BF,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C0,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C1,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C2,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C3,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C4,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C5,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C6,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C7,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C8,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C9,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_CA,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_CB,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_CC,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_CD,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_CE,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_CF,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D0,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D1,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D2,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D3,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D4,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D5,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D6,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D7,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D8,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_D9,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_DA,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_DB,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_DC,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_DD,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_DE,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_DF,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E0,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E1,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E2,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E3,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E4,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E5,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E6,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E7,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E8,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_E9,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_EA,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_EB,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_EC,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_ED,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_EE,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_EF,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F0,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F1,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F2,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F3,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F4,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F5,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F6,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F7,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F8,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F9,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_FA,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_FB,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_FC,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_FD,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_FE,
    MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_FF
} mg_wsgGenericIndex_t;

typedef enum
{
    MG_EDGE_NONE,
    MG_EDGE_TOP,
    MG_EDGE_BOTTOM,
    MG_EDGE_TB,
    MG_EDGE_LEFT,
    MG_EDGE_TL,
    MG_EDGE_BL,
    MG_EDGE_BLT,
    MG_EDGE_RIGHT,
    MG_EDGE_TR,
    MG_EDGE_BR,
    MG_EDGE_TBR,
    MG_EDGE_LR,
    MG_EDGE_TLR,
    MG_EDGE_BLR,
    MG_EDGE_TBLR
} mgEdge_t;

/*
static const int MG_1x2_TILE_COLLISION_OFFSETS_IN_PIXELS[]
    = {0, 8, MG_EDGE_BLR, 0, -8, MG_EDGE_TLR};

static const int MG_TILE_COLLISION_OFFSETS_1x2_BOTTOM_EDGE[]
    = {-7, 15, 0, 15, 6, 15};

static const int MG_TILE_COLLISION_OFFSETS_1x2_TOP_EDGE[]
    = {-7, -15, 0, -15, 7, -15};

static const int MG_TILE_COLLISION_OFFSETS_1x2_RIGHT_EDGE[]
    = {8, 14, 8, 0, 8, -14};

static const int MG_TILE_COLLISION_OFFSETS_1x2_LEFT_EDGE[]
    = {-7, 14, -7, 0, -7, -14};
*/

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_1x2_bottomEdge
    = {.collisionPoints = {{.x = -7, .y = 15}, {.x = 0, .y = 15}, {.x = 6, .y = 15}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_1x2_topEdge
    = {.collisionPoints = {{.x = -7, .y = -15}, {.x = 0, .y = -15}, {.x = 7, .y = -15}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_1x2_rightEdge
    = {.collisionPoints = {{.x = 8, .y = 14}, {.x = 8, .y = 0}, {.x = 8, .y = -14}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_1x2_leftEdge
    = {.collisionPoints = {{.x = -7, .y = 14}, {.x = -7, .y = 0}, {.x = -7, .y = -14}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_1x2_topEdge_dash_slide
    = {.collisionPoints = {{.x = -7, .y = 0}, {.x = 0, .y = 0}, {.x = 7, .y = -0}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_1x2_rightEdge_dash_slide
    = {.collisionPoints = {{.x = 8, .y = 14}, {.x = 8, .y = 0}, {.x = 8, .y = 1}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_1x2_leftEdge_dash_slide
    = {.collisionPoints = {{.x = -7, .y = 14}, {.x = -7, .y = 0}, {.x = -7, .y = 1}}, .size = 3};

static const mg_EntityTileCollider_t entityTileCollider_1x2 = {.bottomEdge = &mgTileCollisionOffsets_1x2_bottomEdge,
                                                               .topEdge    = &mgTileCollisionOffsets_1x2_topEdge,
                                                               .rightEdge  = &mgTileCollisionOffsets_1x2_rightEdge,
                                                               .leftEdge   = &mgTileCollisionOffsets_1x2_leftEdge};

static const mg_EntityTileCollider_t entityTileCollider_1x2_dash_slide
    = {.bottomEdge = &mgTileCollisionOffsets_1x2_bottomEdge,
       .topEdge    = &mgTileCollisionOffsets_1x2_topEdge_dash_slide,
       .rightEdge  = &mgTileCollisionOffsets_1x2_rightEdge_dash_slide,
       .leftEdge   = &mgTileCollisionOffsets_1x2_leftEdge_dash_slide};

// sever yataga origin: 49, 35
static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_sever_yataga_bottomEdge
    = {.collisionPoints = {{.x = -17, .y = 35}, {.x = 0, .y = 35}, {.x = 16, .y = 35}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_sever_yataga_topEdge
    = {.collisionPoints = {{.x = -17, .y = -19}, {.x = 0, .y = -19}, {.x = 16, .y = -19}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_sever_yataga_rightEdge
    = {.collisionPoints = {{.x = 16, .y = 35}, {.x = 16, .y = 0}, {.x = 16, .y = -19}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_sever_yataga_leftEdge
    = {.collisionPoints = {{.x = -17, .y = 35}, {.x = -17, .y = 0}, {.x = -17, .y = -19}}, .size = 3};

static const mg_EntityTileCollider_t entityTileCollider_sever_yataga
    = {.bottomEdge = &mgTileCollisionOffsets_sever_yataga_bottomEdge,
       .topEdge    = &mgTileCollisionOffsets_sever_yataga_topEdge,
       .rightEdge  = &mgTileCollisionOffsets_sever_yataga_rightEdge,
       .leftEdge   = &mgTileCollisionOffsets_sever_yataga_leftEdge};

// smash gorilla origin: 49, 35
static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_smash_gorilla_bottomEdge
    = {.collisionPoints = {{.x = -15, .y = 34}, {.x = 0, .y = 34}, {.x = 14, .y = 34}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_smash_gorilla_topEdge
    = {.collisionPoints = {{.x = -15, .y = -25}, {.x = 0, .y = -25}, {.x = 14, .y = -25}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_smash_gorilla_rightEdge
    = {.collisionPoints = {{.x = 14, .y = 34}, {.x = 14, .y = 0}, {.x = 14, .y = -25}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_smash_gorilla_leftEdge
    = {.collisionPoints = {{.x = -15, .y = 34}, {.x = -15, .y = 0}, {.x = -15, .y = -25}}, .size = 3};

static const mg_EntityTileCollider_t entityTileCollider_smash_gorilla
    = {.bottomEdge = &mgTileCollisionOffsets_smash_gorilla_bottomEdge,
       .topEdge    = &mgTileCollisionOffsets_smash_gorilla_topEdge,
       .rightEdge  = &mgTileCollisionOffsets_smash_gorilla_rightEdge,
       .leftEdge   = &mgTileCollisionOffsets_smash_gorilla_leftEdge};

// grind pangolin origin: 33, 28
static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_grind_pangolin_bottomEdge
    = {.collisionPoints = {{.x = -30, .y = 27}, {.x = 0, .y = 27}, {.x = 30, .y = 27}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_grind_pangolin_topEdge
    = {.collisionPoints = {{.x = -30, .y = -11}, {.x = 0, .y = -11}, {.x = 30, .y = -11}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_grind_pangolin_rightEdge
    = {.collisionPoints = {{.x = 30, .y = 27}, {.x = 30, .y = 0}, {.x = 30, .y = -11}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_grind_pangolin_leftEdge
    = {.collisionPoints = {{.x = -30, .y = 27}, {.x = -30, .y = 0}, {.x = -30, .y = -11}}, .size = 3};

static const mg_EntityTileCollider_t entityTileCollider_grind_pangolin
    = {.bottomEdge = &mgTileCollisionOffsets_grind_pangolin_bottomEdge,
       .topEdge    = &mgTileCollisionOffsets_grind_pangolin_topEdge,
       .rightEdge  = &mgTileCollisionOffsets_grind_pangolin_rightEdge,
       .leftEdge   = &mgTileCollisionOffsets_grind_pangolin_leftEdge};

// grind pangolin rolling origin: 19, 15
static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_grind_pangolin_rolling_bottomEdge
    = {.collisionPoints = {{.x = -10, .y = 15}, {.x = 0, .y = 15}, {.x = 10, .y = 15}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_grind_pangolin_rolling_topEdge
    = {.collisionPoints = {{.x = -10, .y = -15}, {.x = 0, .y = -15}, {.x = 10, .y = -15}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_grind_pangolin_rolling_rightEdge
    = {.collisionPoints = {{.x = 10, .y = 15}, {.x = 10, .y = 0}, {.x = 10, .y = -15}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_grind_pangolin_rolling_leftEdge
    = {.collisionPoints = {{.x = -10, .y = 15}, {.x = -10, .y = 0}, {.x = -10, .y = -15}}, .size = 3};

static const mg_EntityTileCollider_t entityTileCollider_grind_pangolin_rolling
    = {.bottomEdge = &mgTileCollisionOffsets_grind_pangolin_rolling_bottomEdge,
       .topEdge    = &mgTileCollisionOffsets_grind_pangolin_rolling_topEdge,
       .rightEdge  = &mgTileCollisionOffsets_grind_pangolin_rolling_rightEdge,
       .leftEdge   = &mgTileCollisionOffsets_grind_pangolin_rolling_leftEdge};

// drain bat origin: 30, 31
static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_drain_bat_bottomEdge
    = {.collisionPoints = {{.x = -17, .y = 63}, {.x = 0, .y = 63}, {.x = 17, .y = 63}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_drain_bat_topEdge
    = {.collisionPoints = {{.x = -17, .y = -15}, {.x = 0, .y = -15}, {.x = 17, .y = -15}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_drain_bat_rightEdge
    = {.collisionPoints = {{.x = 17, .y = 63}, {.x = 17, .y = 0}, {.x = 17, .y = -15}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_drain_bat_leftEdge
    = {.collisionPoints = {{.x = -17, .y = 63}, {.x = -17, .y = 0}, {.x = -17, .y = -15}}, .size = 3};

static const mg_EntityTileCollider_t entityTileCollider_drain_bat
    = {.bottomEdge = &mgTileCollisionOffsets_drain_bat_bottomEdge,
       .topEdge    = &mgTileCollisionOffsets_drain_bat_topEdge,
       .rightEdge  = &mgTileCollisionOffsets_drain_bat_rightEdge,
       .leftEdge   = &mgTileCollisionOffsets_drain_bat_leftEdge};

// kinetic donut origin: 21, 25
static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_kinetic_donut_bottomEdge
    = {.collisionPoints = {{.x = -16, .y = 24}, {.x = 0, .y = 24}, {.x = 16, .y = 24}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_kinetic_donut_topEdge
    = {.collisionPoints = {{.x = -16, .y = -9}, {.x = 0, .y = -9}, {.x = 16, .y = -9}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_kinetic_donut_rightEdge
    = {.collisionPoints = {{.x = 16, .y = 24}, {.x = 16, .y = 0}, {.x = 16, .y = -9}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_kinetic_donut_leftEdge
    = {.collisionPoints = {{.x = -16, .y = 24}, {.x = -13, .y = 0}, {.x = -16, .y = -9}}, .size = 3};

static const mg_EntityTileCollider_t entityTileCollider_kinetic_donut
    = {.bottomEdge = &mgTileCollisionOffsets_kinetic_donut_bottomEdge,
       .topEdge    = &mgTileCollisionOffsets_kinetic_donut_topEdge,
       .rightEdge  = &mgTileCollisionOffsets_kinetic_donut_rightEdge,
       .leftEdge   = &mgTileCollisionOffsets_kinetic_donut_leftEdge};

// flare gryffyn origin: 40, 32
static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_flare_gryffyn_bottomEdge
    = {.collisionPoints = {{.x = -24, .y = 30}, {.x = 0, .y = 30}, {.x = 24, .y = 30}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_flare_gryffyn_topEdge
    = {.collisionPoints = {{.x = -24, .y = -32}, {.x = 0, .y = -32}, {.x = 24, .y = -32}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_flare_gryffyn_rightEdge
    = {.collisionPoints = {{.x = 24, .y = 30}, {.x = 24, .y = 0}, {.x = 24, .y = -32}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_flare_gryffyn_leftEdge
    = {.collisionPoints = {{.x = -24, .y = 30}, {.x = -24, .y = 0}, {.x = -24, .y = -32}}, .size = 3};

static const mg_EntityTileCollider_t entityTileCollider_flare_gryffyn
    = {.bottomEdge = &mgTileCollisionOffsets_flare_gryffyn_bottomEdge,
       .topEdge    = &mgTileCollisionOffsets_flare_gryffyn_topEdge,
       .rightEdge  = &mgTileCollisionOffsets_flare_gryffyn_rightEdge,
       .leftEdge   = &mgTileCollisionOffsets_flare_gryffyn_leftEdge};

// flare gryffyn jumping origin: 48, 44
static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_flare_gryffyn_jumping_bottomEdge
    = {.collisionPoints = {{.x = -19, .y = 41}, {.x = 0, .y = 41}, {.x = 18, .y = 41}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_flare_gryffyn_jumping_topEdge
    = {.collisionPoints = {{.x = -19, .y = -44}, {.x = 0, .y = -44}, {.x = 18, .y = -44}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_flare_gryffyn_jumping_rightEdge
    = {.collisionPoints = {{.x = 18, .y = 41}, {.x = 18, .y = 0}, {.x = 18, .y = -44}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_flare_gryffyn_jumping_leftEdge
    = {.collisionPoints = {{.x = -19, .y = 41}, {.x = -19, .y = 0}, {.x = -19, .y = -44}}, .size = 3};

static const mg_EntityTileCollider_t entityTileCollider_flare_gryffyn_jumping
    = {.bottomEdge = &mgTileCollisionOffsets_flare_gryffyn_jumping_bottomEdge,
       .topEdge    = &mgTileCollisionOffsets_flare_gryffyn_jumping_topEdge,
       .rightEdge  = &mgTileCollisionOffsets_flare_gryffyn_jumping_rightEdge,
       .leftEdge   = &mgTileCollisionOffsets_flare_gryffyn_jumping_leftEdge};

// deadeye chirpzi origin: 40, 34
static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_deadeye_chirpzi_bottomEdge
    = {.collisionPoints = {{.x = -17, .y = 33}, {.x = 0, .y = 33}, {.x = 16, .y = 33}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_deadeye_chirpzi_topEdge
    = {.collisionPoints = {{.x = -17, .y = -29}, {.x = 0, .y = -29}, {.x = 16, .y = -29}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_deadeye_chirpzi_rightEdge
    = {.collisionPoints = {{.x = 16, .y = 33}, {.x = 16, .y = 0}, {.x = 16, .y = -29}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_deadeye_chirpzi_leftEdge
    = {.collisionPoints = {{.x = -17, .y = 33}, {.x = -17, .y = 0}, {.x = -17, .y = -29}}, .size = 3};

static const mg_EntityTileCollider_t entityTileCollider_deadeye_chirpzi
    = {.bottomEdge = &mgTileCollisionOffsets_deadeye_chirpzi_bottomEdge,
       .topEdge    = &mgTileCollisionOffsets_deadeye_chirpzi_topEdge,
       .rightEdge  = &mgTileCollisionOffsets_deadeye_chirpzi_rightEdge,
       .leftEdge   = &mgTileCollisionOffsets_deadeye_chirpzi_leftEdge};

// trash man origin: 38, 33
static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_trash_man_bottomEdge
    = {.collisionPoints = {{.x = -30, .y = 32}, {.x = 0, .y = 32}, {.x = 30, .y = 32}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_trash_man_topEdge
    = {.collisionPoints = {{.x = -30, .y = -29}, {.x = 0, .y = -29}, {.x = 30, .y = -29}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_trash_man_rightEdge
    = {.collisionPoints = {{.x = 30, .y = 32}, {.x = 30, .y = 0}, {.x = 30, .y = -29}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_trash_man_leftEdge
    = {.collisionPoints = {{.x = -30, .y = 32}, {.x = -30, .y = 0}, {.x = -30, .y = -29}}, .size = 3};

static const mg_EntityTileCollider_t entityTileCollider_trash_man
    = {.bottomEdge = &mgTileCollisionOffsets_trash_man_bottomEdge,
       .topEdge    = &mgTileCollisionOffsets_trash_man_topEdge,
       .rightEdge  = &mgTileCollisionOffsets_trash_man_rightEdge,
       .leftEdge   = &mgTileCollisionOffsets_trash_man_leftEdge};

// bigma origin: 33, 44
static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_bigma_bottomEdge
    = {.collisionPoints = {{.x = -17, .y = 42}, {.x = 0, .y = 42}, {.x = 17, .y = 42}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_bigma_topEdge
    = {.collisionPoints = {{.x = -17, .y = -44}, {.x = 0, .y = -44}, {.x = 17, .y = -44}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_bigma_rightEdge
    = {.collisionPoints = {{.x = 17, .y = 42}, {.x = 17, .y = 0}, {.x = 17, .y = -44}}, .size = 3};

static const mg_EntityTileCollisionPointList_t mgTileCollisionOffsets_bigma_leftEdge
    = {.collisionPoints = {{.x = -17, .y = 42}, {.x = -17, .y = 0}, {.x = -17, .y = -44}}, .size = 3};

static const mg_EntityTileCollider_t entityTileCollider_bigma = {.bottomEdge = &mgTileCollisionOffsets_bigma_bottomEdge,
                                                                 .topEdge    = &mgTileCollisionOffsets_bigma_topEdge,
                                                                 .rightEdge  = &mgTileCollisionOffsets_bigma_rightEdge,
                                                                 .leftEdge   = &mgTileCollisionOffsets_bigma_leftEdge};

typedef enum
{
    MG_WSGSET_NULL = -1,
    MG_WSGSET_DEFAULT,
    MG_WSGSET_LEVEL_SELECT,
    MG_WSGSET_KINETIC_DONUT,
    MG_WSGSET_SMASH_GORILLA,
    MG_WSGSET_DRAIN_BAT,
    MG_WSGSET_DEADEYE_CHIRPZI,
    MG_WSGSET_SEVER_YATAGA,
    MG_WSGSET_GRIND_PANGOLIN,
    MG_WSGSET_FLARE_GRYFFYN,
    MG_WSGSET_TRASH_MAN,
    MG_WSGSET_BIGMA
} mgWsgSetIndex_t;

// Note: none of these names match actual colors
static const paletteColor_t bgGradientGray[]   = {c001, c112, c223, c334};
static const paletteColor_t bgGradientPurple[] = {c202, c203, c204, c205};
static const paletteColor_t bgGradientBlue[]   = {c102, c103, c104, c105};
static const paletteColor_t bgGradientCyan[]   = {c003, c013, c023, c033};
static const paletteColor_t bgGradientGreen[]  = {c001, c111, c221, c331};
static const paletteColor_t bgGradientYellow[] = {c202, c312, c422, c532};
static const paletteColor_t bgGradientOrange[] = {c040, c230, c220, c210};
static const paletteColor_t bgGradientRed[]    = {c101, c201, c301, c411};
static const paletteColor_t bgGradientMenu[]   = {c001, c012, c123, c234};

static const mgLeveldef_t leveldef[] = {
    {.filename           = LEVEL_SELECT_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_LEVEL_SELECT,
     .mainBgmIndex       = MG_BGM_STAGE_SELECT,
     .bossBgmIndex       = MG_BGM_NULL,
     .bgColors           = bgGradientMenu},
    {.filename           = DONUT_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_KINETIC_DONUT,
     .mainBgmIndex       = MG_BGM_KINETIC_DONUT,
     .bossBgmIndex       = MG_BGM_BOSS_KINETIC_DONUT,
     .bgColors           = bgGradientBlue},
    {.filename           = GRIND_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_GRIND_PANGOLIN,
     .mainBgmIndex       = MG_BGM_GRIND_PANGOLIN,
     .bossBgmIndex       = MG_BGM_BOSS_GRIND_PANGOLIN,
     .bgColors           = bgGradientPurple},
    {.filename           = SEVER_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_SEVER_YATAGA,
     .mainBgmIndex       = MG_BGM_SEVER_YAGATA,
     .bossBgmIndex       = MG_BGM_BOSS_SEVER_YAGATA,
     .bgColors           = bgGradientCyan},
    {.filename           = DUMP_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_TRASH_MAN,
     .mainBgmIndex       = MG_BGM_RIP_BARONESS,
     .bossBgmIndex       = MG_BGM_BOSS_TRASH_MAN,
     .bgColors           = bgGradientOrange},
    {.filename           = GAUNTLET_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_BIGMA,
     .mainBgmIndex       = MG_BGM_KINETIC_DONUT,
     .bossBgmIndex       = MG_BGM_BOSS_BIGMA,
     .bgColors           = bgGradientMenu},
    {.filename           = SMASH_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_SMASH_GORILLA,
     .mainBgmIndex       = MG_BGM_SMASH_GORILLA,
     .bossBgmIndex       = MG_BGM_BOSS_SMASH_GORILLA,
     .bgColors           = bgGradientYellow},
    {.filename           = DEADEYE_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_DEADEYE_CHIRPZI,
     .mainBgmIndex       = MG_BGM_DEADEYE_CHIRPZI,
     .bossBgmIndex       = MG_BGM_BOSS_DEADEYE_CHIRPZI,
     .bgColors           = bgGradientGreen},
    {.filename           = DRAIN_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_DRAIN_BAT,
     .mainBgmIndex       = MG_BGM_DRAIN_BAT,
     .bossBgmIndex       = MG_BGM_BOSS_DRAIN_BAT,
     .bgColors           = bgGradientGray},
    {.filename           = GRYFFYN_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_FLARE_GRYFFYN,
     .mainBgmIndex       = MG_BGM_FLARE_GRYFFYN,
     .bossBgmIndex       = MG_BGM_BOSS_FLARE_GRYFFYN,
     .bgColors           = bgGradientRed},
    {.filename           = BOSS_TEST_ROOM_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_KINETIC_DONUT,
     .mainBgmIndex       = MG_BGM_KINETIC_DONUT,
     .bossBgmIndex       = MG_BGM_BOSS_SEVER_YAGATA,
     .bgColors           = bgGradientPurple},
    {.filename           = BOSS_TEST_DONUT_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_KINETIC_DONUT,
     .mainBgmIndex       = MG_BGM_KINETIC_DONUT,
     .bossBgmIndex       = MG_BGM_BOSS_KINETIC_DONUT,
     .bgColors           = bgGradientBlue},
    {.filename           = BOSS_TEST_GRIND_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_GRIND_PANGOLIN,
     .mainBgmIndex       = MG_BGM_GRIND_PANGOLIN,
     .bossBgmIndex       = MG_BGM_BOSS_GRIND_PANGOLIN,
     .bgColors           = bgGradientPurple},
    {.filename           = BOSS_TEST_SEVER_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_SEVER_YATAGA,
     .mainBgmIndex       = MG_BGM_SEVER_YAGATA,
     .bossBgmIndex       = MG_BGM_BOSS_SEVER_YAGATA,
     .bgColors           = bgGradientCyan},
    {.filename           = BOSS_TEST_TRASH_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_TRASH_MAN,
     .mainBgmIndex       = MG_BGM_RIP_BARONESS,
     .bossBgmIndex       = MG_BGM_BOSS_TRASH_MAN,
     .bgColors           = bgGradientOrange},
    {.filename           = BOSS_TEST_BIGMA_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_BIGMA,
     .mainBgmIndex       = MG_BGM_KINETIC_DONUT,
     .bossBgmIndex       = MG_BGM_BOSS_BIGMA,
     .bgColors           = bgGradientMenu},
    {.filename           = BOSS_TEST_SMASH_GORILLA_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_SMASH_GORILLA,
     .mainBgmIndex       = MG_BGM_SMASH_GORILLA,
     .bossBgmIndex       = MG_BGM_BOSS_SMASH_GORILLA,
     .bgColors           = bgGradientYellow},
    {.filename           = BOSS_TEST_DEADEYE_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_DEADEYE_CHIRPZI,
     .mainBgmIndex       = MG_BGM_DEADEYE_CHIRPZI,
     .bossBgmIndex       = MG_BGM_BOSS_DEADEYE_CHIRPZI,
     .bgColors           = bgGradientGreen},
    {.filename           = BOSS_TEST_DRAIN_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_DRAIN_BAT,
     .mainBgmIndex       = MG_BGM_DRAIN_BAT,
     .bossBgmIndex       = MG_BGM_BOSS_DRAIN_BAT,
     .bgColors           = bgGradientGray},
    {.filename           = BOSS_TEST_FLARE_BIN,
     .timeLimit          = 180,
     .defaultWsgSetIndex = MG_WSGSET_FLARE_GRYFFYN,
     .mainBgmIndex       = MG_BGM_FLARE_GRYFFYN,
     .bossBgmIndex       = MG_BGM_BOSS_FLARE_GRYFFYN,
     .bgColors           = bgGradientRed},
};

static const mg_spriteDef_t playerDamageAnimFrames[]
    = {MG_SP_PLAYER_HURT, MG_SP_PLAYER_HURT_2, MG_SP_PLAYER_HURT, MG_SP_PLAYER_HURT_3};
static const mg_spriteDef_t playerMicDropAnimFrames[]     = {MG_SP_PLAYER_MIC_DROP_1, MG_SP_PLAYER_MIC_DROP_2};
static const mg_spriteDef_t playerSureYouCanAnimnFrames[] = {
    // These are in reverse order
    MG_SP_PLAYER_SUREYOUCAN_2, MG_SP_PLAYER_SUREYOUCAN_2, MG_SP_PLAYER_SUREYOUCAN_2, MG_SP_PLAYER_SUREYOUCAN_1,
    MG_SP_PLAYER_SUREYOUCAN_1, MG_SP_PLAYER_JUMP,         MG_WSG_PLAYER_WALK5,       MG_WSG_PLAYER_WALK6};

static const mg_spriteDef_t normalShotAnimFrames[] = {MG_SP_WAVEBALL_1, MG_SP_WAVEBALL_2, MG_SP_WAVEBALL_3};
static const mg_spriteDef_t chargeShotAnimFrames[]
    = {MG_SP_CHARGE_SHOT_LVL1_1, MG_SP_CHARGE_SHOT_LVL1_2, MG_SP_CHARGE_SHOT_LVL1_3};
static const mg_spriteDef_t maxChargeShotAnimFrames[]
    = {MG_SP_CHARGE_SHOT_MAX_1, MG_SP_CHARGE_SHOT_MAX_2, MG_SP_CHARGE_SHOT_MAX_3};

// platformerTrophies array is defined in megaPulseEx.c to avoid multiple definitions
extern const trophyData_t platformerTrophies[];

extern void goToReadyScreen(void);
extern void initBossFight(void);
extern void startBossOutroCutscene(void);
#endif