#ifndef _MGTILESETCONFIG_H_
#define _MGTILESETCONFIG_H_

#include "mega_pulse_ex_typedef.h"
#include "mgSprite.h"

#define MG_KINETIC_DONUT_TILESET_MAP_LENGTH 99

#define MG_IMAGE_FILENAME_LOOKUP_OFFSET 0
#define MG_WSG_INDEX_LOOKUP_OFFSET      1
#define MG_TILE_INDEX_LOOKUP_OFFSET     2
#define MG_TILESET_MAP_ROW_LENGTH       3

static const uint16_t mg_kineticDonutTileset[] = {
    // CNFS File Index, WSG Index, Tile Index
    KD_TILE_032_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_20,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_20,
    KD_TILE_033_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_21,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_21,
    KD_TILE_034_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_22,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_22,
    KD_TILE_035_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_23,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_23,
    KD_TILE_036_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_24,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_24,
    KD_TILE_037_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_25,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_25,
    KD_TILE_038_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_26,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_26,
    KD_TILE_039_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_27,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_27,
    KD_TILE_040_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_28,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_28,
    KD_TILE_041_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_29,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_29,
    KD_TILE_042_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2A,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2A,
    KD_TILE_043_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2B,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2B,
    KD_TILE_044_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2C,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2C,
    KD_TILE_045_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2D,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2D,
    KD_TILE_046_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2E,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2E,
    KD_TILE_047_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2F,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2F,
    KD_TILE_048_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_30,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_30,
    KD_TILE_049_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_31,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_31,
    KD_TILE_050_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_32,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_32,
    KD_TILE_051_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_33,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_33,
    KD_TILE_052_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_34,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_34,
    KD_TILE_053_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_35,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_35,
    KD_TILE_054_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_36,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_36,
    KD_TILE_055_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_37,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_37,
    KD_TILE_056_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_38,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_38,
    KD_TILE_057_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_39,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_39,
    KD_TILE_058_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3A,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3A,
    KD_TILE_059_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3B,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3B,
    KD_TILE_060_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3C,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3C,
    KD_TILE_061_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3D,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3D,
    KD_TILE_062_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3E,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3E,
    KD_TILE_063_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3F,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3F,
    KD_TILE_064_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_40,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_40,
    KD_TILE_065_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_41,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_41,
    KD_TILE_066_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_42,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_42,
    KD_TILE_067_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_43,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_43,
    KD_TILE_068_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_44,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_44,
    KD_TILE_069_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_45,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_45,
    KD_TILE_070_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_46,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_46,
    KD_TILE_071_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_47,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_47,
    KD_TILE_072_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_48,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_48,
    KD_TILE_073_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_49,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_49,
    KD_TILE_074_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4A,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4A,
    KD_TILE_075_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4B,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4B,
    KD_TILE_076_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4C,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4C,
    KD_TILE_077_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4D,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4D,
    KD_TILE_078_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4E,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4E,
    KD_TILE_079_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4F,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4F,
    KD_TILE_080_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_50,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_50,
    KD_TILE_081_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_51,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_51,
    KD_TILE_082_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_52,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_52,
    KD_TILE_083_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_53,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_53,
    KD_TILE_084_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_54,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_54,
    KD_TILE_085_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_55,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_55,
    KD_TILE_086_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_56,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_56,
    KD_TILE_087_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_57,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_57,
    KD_TILE_088_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_58,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_58,
    KD_TILE_089_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_59,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_59,
    KD_TILE_090_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5A,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5A,
    KD_TILE_091_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5B,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5B,
    KD_TILE_092_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5C,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5C,
    KD_TILE_093_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5D,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5D,
    KD_TILE_094_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5E,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5E,
    KD_TILE_095_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5F,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5F,
    KD_TILE_096_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_60,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_60,
    KD_TILE_097_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_61,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_61,
    KD_TILE_098_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_62,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_62,
    KD_TILE_099_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_63,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_63,
    KD_TILE_100_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_64,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_64,
    KD_TILE_101_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_65,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_65,
    KD_TILE_102_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_66,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_66,
    KD_TILE_103_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_67,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_67,
    KD_TILE_104_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_68,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_68,
    KD_TILE_105_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_69,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_69,
    KD_TILE_106_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6A,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6A,
    KD_TILE_107_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6B,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6B,
    KD_TILE_108_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6C,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6C,
    KD_TILE_109_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6D,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6D,
    KD_TILE_110_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6E,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6E,
    KD_TILE_160_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A0,    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A0,
    TILE_039_WSG,    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A1,    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A1,
    SPIKE_TILE_TOP_00_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A2, MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A2,
    SPIKE_TILE_LEFT_00_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A3, MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A3,
    SPIKE_TILE_BOTTOM_00_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A4, MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A4,
    SPIKE_TILE_RIGHT_00_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A5, MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A5,
    TILE_034_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A6, MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A6,
    KD_TILE_192_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C0, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C0,
    KD_TILE_193_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C1, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C1,
    KD_TILE_194_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C2, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C2,
    KD_TILE_195_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C3, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C3,
    KD_TILE_196_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C4, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C4,
    KD_TILE_197_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C5, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C5,
    
    //Space reserved for tile animation frames

    //Boss sprites are part of level tileset
    SEVER_YATAGA_000_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F0, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F0,
    SEVER_YATAGA_001_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F1, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F1,
    SEVER_YATAGA_002_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F2, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F2,
    SEVER_YATAGA_003_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F3, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F3,
    SEVER_YATAGA_004_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F4, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F4,
    SEVER_YATAGA_005_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F5, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F5,
    SEVER_YATAGA_006_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F6, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F6,
};

static const mgSprite_t mg_kineticDounutBossSpriteMetadataSet[] = {
    {
        .wsg = NULL,
        .origin = &origin_sever_yataga,
        .hitBox = &box_sever_yataga
    },
    {
        .wsg = NULL,
        .origin = &origin_sever_yataga,
        .hitBox = &box_sever_yataga
    },
    {
        .wsg = NULL,
        .origin = &origin_sever_yataga,
        .hitBox = &box_sever_yataga
    },
    {
        .wsg = NULL,
        .origin = &origin_sever_yataga,
        .hitBox = &box_sever_yataga
    },
    {
        .wsg = NULL,
        .origin = &origin_sever_yataga,
        .hitBox = &box_sever_yataga
    },
    {
        .wsg = NULL,
        .origin = &origin_sever_yataga,
        .hitBox = &box_sever_yataga
    },
    {
        .wsg = NULL,
        .origin = &origin_sever_yataga,
        .hitBox = &box_sever_yataga
    },
    {
        .wsg = NULL,
        .origin = NULL,
        .hitBox = NULL
    }
};

bool mg_kineticDonutTileset_needsTransparency(uint8_t tileId);
void mg_kineticDonutTileset_animateTiles(uint8_t tileId);

#define MG_LEVEL_SELECT_TILESET_MAP_LENGTH 10

static const uint16_t mg_levelSelectTileset[] = {
    // CNFS File Index, WSG Index, Tile Index
    MG_LEVEL_SELECT_TILE_001_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_20, MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_20,
    MG_LEVEL_SELECT_TILE_002_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_21, MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_21,
    MG_LEVEL_SELECT_TILE_003_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_22, MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_22,
    MG_LEVEL_SELECT_TILE_004_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_23, MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_23,
    MG_LEVEL_SELECT_TILE_005_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_24, MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_24,
    MG_LEVEL_SELECT_TILE_006_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_25, MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_25,
    MG_LEVEL_SELECT_TILE_007_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_26, MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_26,
    MG_LEVEL_SELECT_TILE_008_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_27, MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_27,
    MG_LEVEL_SELECT_TILE_009_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_28, MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_28,
    MG_LEVEL_SELECT_TILE_010_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_29, MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_29,
};

bool mg_levelSelectTileset_needsTransparency(uint8_t tileId);
void mg_levelSelectTileset_animateTiles(uint8_t tileId);


//Length, transparency, animate shared with kineticDonutTileset
static const uint16_t mg_smashGorillaTileset[] = {
    // CNFS File Index, WSG Index, Tile Index
    YE_TILE_032_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_20,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_20,
    YE_TILE_033_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_21,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_21,
    YE_TILE_034_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_22,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_22,
    YE_TILE_035_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_23,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_23,
    YE_TILE_036_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_24,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_24,
    YE_TILE_037_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_25,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_25,
    YE_TILE_038_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_26,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_26,
    YE_TILE_039_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_27,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_27,
    YE_TILE_040_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_28,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_28,
    YE_TILE_041_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_29,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_29,
    YE_TILE_042_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2A,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2A,
    YE_TILE_043_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2B,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2B,
    YE_TILE_044_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2C,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2C,
    KD_TILE_045_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2D,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2D,
    KD_TILE_046_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2E,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2E,
    KD_TILE_047_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2F,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_2F,
    KD_TILE_048_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_30,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_30,
    KD_TILE_049_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_31,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_31,
    KD_TILE_050_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_32,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_32,
    KD_TILE_051_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_33,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_33,
    KD_TILE_052_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_34,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_34,
    KD_TILE_053_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_35,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_35,
    KD_TILE_054_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_36,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_36,
    KD_TILE_055_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_37,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_37,
    KD_TILE_056_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_38,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_38,
    KD_TILE_057_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_39,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_39,
    KD_TILE_058_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3A,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3A,
    KD_TILE_059_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3B,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3B,
    KD_TILE_060_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3C,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3C,
    KD_TILE_061_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3D,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3D,
    KD_TILE_062_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3E,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3E,
    KD_TILE_063_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3F,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_3F,
    KD_TILE_064_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_40,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_40,
    KD_TILE_065_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_41,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_41,
    KD_TILE_066_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_42,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_42,
    KD_TILE_067_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_43,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_43,
    KD_TILE_068_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_44,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_44,
    KD_TILE_069_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_45,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_45,
    KD_TILE_070_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_46,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_46,
    KD_TILE_071_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_47,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_47,
    KD_TILE_072_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_48,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_48,
    KD_TILE_073_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_49,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_49,
    KD_TILE_074_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4A,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4A,
    KD_TILE_075_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4B,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4B,
    KD_TILE_076_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4C,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4C,
    KD_TILE_077_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4D,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4D,
    KD_TILE_078_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4E,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4E,
    KD_TILE_079_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4F,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_4F,
    KD_TILE_080_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_50,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_50,
    KD_TILE_081_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_51,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_51,
    KD_TILE_082_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_52,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_52,
    KD_TILE_083_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_53,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_53,
    KD_TILE_084_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_54,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_54,
    KD_TILE_085_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_55,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_55,
    KD_TILE_086_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_56,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_56,
    KD_TILE_087_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_57,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_57,
    KD_TILE_088_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_58,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_58,
    KD_TILE_089_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_59,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_59,
    KD_TILE_090_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5A,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5A,
    KD_TILE_091_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5B,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5B,
    KD_TILE_092_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5C,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5C,
    KD_TILE_093_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5D,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5D,
    KD_TILE_094_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5E,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5E,
    KD_TILE_095_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5F,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_5F,
    KD_TILE_096_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_60,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_60,
    KD_TILE_097_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_61,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_61,
    KD_TILE_098_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_62,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_62,
    KD_TILE_099_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_63,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_63,
    KD_TILE_100_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_64,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_64,
    KD_TILE_101_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_65,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_65,
    KD_TILE_102_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_66,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_66,
    KD_TILE_103_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_67,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_67,
    KD_TILE_104_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_68,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_68,
    KD_TILE_105_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_69,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_69,
    KD_TILE_106_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6A,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6A,
    KD_TILE_107_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6B,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6B,
    KD_TILE_108_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6C,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6C,
    KD_TILE_109_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6D,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6D,
    KD_TILE_110_WSG, MG_WSG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6E,    MG_TILE_SOLID_VISIBLE_NONINTERACTIVE_6E,
    KD_TILE_160_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A0,    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A0,
    TILE_039_WSG,    MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A1,    MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A1,
    SPIKE_TILE_TOP_00_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A2, MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A2,
    SPIKE_TILE_LEFT_00_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A3, MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A3,
    SPIKE_TILE_BOTTOM_00_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A4, MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A4,
    SPIKE_TILE_RIGHT_00_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A5, MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A5,
    TILE_034_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A6, MG_TILE_NONSOLID_VISIBLE_INTERACTIVE_A6,
    KD_TILE_192_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C0, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C0,
    KD_TILE_193_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C1, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C1,
    KD_TILE_194_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C2, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C2,
    KD_TILE_195_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C3, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C3,
    KD_TILE_196_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C4, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C4,
    KD_TILE_197_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C5, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_C5,
    
    //Space reserved for tile animation frames

    //Boss sprites are part of level tileset
    SMASH_GORILLA_000_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F0, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F0,
    SMASH_GORILLA_001_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F1, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F1,
    SMASH_GORILLA_002_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F2, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F2,
    SMASH_GORILLA_003_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F3, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F3,
    SMASH_GORILLA_004_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F4, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F4,
    SMASH_GORILLA_005_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F5, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F5,
    SMASH_GORILLA_006_WSG, MG_WSG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F6, MG_TILE_NONSOLID_VISIBLE_NONINTERACTIVE_F6,
};

static const mgSprite_t mg_smashGorillaBossSpriteMetadataSet[] = {
    {
        .wsg = NULL,
        .origin = &origin_sever_yataga,
        .hitBox = &box_sever_yataga
    },
    {
        .wsg = NULL,
        .origin = &origin_sever_yataga,
        .hitBox = &box_sever_yataga
    },
    {
        .wsg = NULL,
        .origin = &origin_sever_yataga,
        .hitBox = &box_sever_yataga
    },
    {
        .wsg = NULL,
        .origin = &origin_sever_yataga,
        .hitBox = &box_sever_yataga
    },
    {
        .wsg = NULL,
        .origin = &origin_sever_yataga,
        .hitBox = &box_sever_yataga
    },
    {
        .wsg = NULL,
        .origin = &origin_sever_yataga,
        .hitBox = &box_sever_yataga
    },
    {
        .wsg = NULL,
        .origin = &origin_sever_yataga,
        .hitBox = &box_sever_yataga
    },
    {
        .wsg = NULL,
        .origin = NULL,
        .hitBox = NULL
    }
};

#endif