#include "hdw-bzr.h"
#include "paint_song.h"

static musicalNote_t paintBgmNotes[] = {
    {.note = A_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = D_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_3, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = D_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = C_SHARP_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = C_SHARP_5, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = D_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = C_SHARP_4, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = A_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_4, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = F_SHARP_2, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = C_SHARP_5, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = D_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = A_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = D_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = F_SHARP_3, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = D_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = C_SHARP_4, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = C_SHARP_5, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = D_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = A_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = C_SHARP_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = F_SHARP_4, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = C_SHARP_5, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = D_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_4, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = B_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = D_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = B_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = A_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = B_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = F_SHARP_3, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = F_SHARP_3, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = D_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = D_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = A_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = B_1, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_2, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = F_SHARP_4, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = B_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = D_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = B_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = B_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_2, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = A_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = D_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = D_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = B_1, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = F_SHARP_2, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = E_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = D_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = G_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = G_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = E_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = E_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = G_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = E_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = D_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = D_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = G_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = A_1, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = E_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = E_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = A_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = D_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = G_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = G_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = E_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = E_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = G_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = E_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = D_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = D_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = G_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_1, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = E_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = B_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = E_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_1, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = E_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = C_SHARP_4, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = A_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = E_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = B_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = D_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = E_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_1, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = G_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = E_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_1, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = E_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = C_SHARP_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = A_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_1, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_1, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = A_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = E_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = E_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = C_SHARP_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = E_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = F_SHARP_4, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = E_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = E_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = B_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = C_SHARP_4, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = F_SHARP_2, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = A_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_2, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = E_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_2, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = C_SHARP_3, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = C_SHARP_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = E_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = C_SHARP_3, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = A_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_1, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = E_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_1, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = C_SHARP_2, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = C_SHARP_4, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = F_SHARP_2, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = E_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = F_SHARP_2, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = C_SHARP_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = C_SHARP_2, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = E_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = C_SHARP_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = A_1, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = E_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_1, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = C_SHARP_2, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = B_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = D_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = B_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = A_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = B_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_3, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = F_SHARP_2, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = A_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_3, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = D_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = D_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = B_1, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_4, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = B_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = D_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = B_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = A_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = B_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = F_SHARP_3, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = F_SHARP_3, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = D_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = D_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = A_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = B_1, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = F_SHARP_2, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},
    {.note = B_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = E_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = G_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = E_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = D_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = D_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = E_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = B_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = B_1, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = D_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = B_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = G_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = G_1, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = D_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = E_1, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = B_1, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = C_SHARP_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = A_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = A_2, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = E_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = E_4, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},  {.note = A_2, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = E_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = C_SHARP_2, .timeMs = 62}, {.note = SILENCE, .timeMs = 125},  {.note = E_3, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},  {.note = E_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 125},
    {.note = A_3, .timeMs = 62},       {.note = SILENCE, .timeMs = 500},  {.note = E_4, .timeMs = 62},
    {.note = SILENCE, .timeMs = 125},
};

songTrack_t paintSongTrack = {
    .numNotes      = 442,
    .loopStartNote = 0,
    .notes         = paintBgmNotes,
};

const song_t paintBgm = {
    .numTracks  = 1,
    .shouldLoop = true,
    .tracks     = &paintSongTrack,
};
