//==============================================================================
// Include
//==============================================================================

#include "ci_craftingData.h"

const ciRecipeProto_t recipeList[] = {
    {
        .name          = "Cloth",
        .cs            = CI_CRAFT_WEAVER,
        .items[0].item = CI_COTTON,
        .items[0].qty  = 10,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty  = 0,
        .result        = CI_CLOTH,
    },
    {
        .name          = "Cut Blocks",
        .cs            = CI_CRAFT_STONE_CUTTER,
        .items[0].item = CI_ROCKS,
        .items[0].qty  = 4,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty  = 0,
        .result        = CI_CUT_ROCK,
    },
    {
        .name          = "Diamond",
        .cs            = CI_CRAFT_SMASHER,
        .items[0].item = CI_ROCKS,
        .items[0].qty  = 10,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty  = 0,
        .result        = CI_DIAMOND,
    },
    {
        .name          = "Diamond Powder",
        .cs            = CI_CRAFT_SMASHER,
        .items[0].item = CI_DIAMOND,
        .items[0].qty  = 1,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty  = 0,
        .result        = CI_DIAMOND_POWDER,
    },
    {
        .name          = "Gears",
        .cs            = CI_CRAFT_WORKBENCH,
        .items[0].item = CI_STICK,
        .items[0].qty  = 8,
        .items[1].item = CI_RESIN,
        .items[1].qty  = 5,
        .result        = CI_GEAR,
    },
    {
        .name          = "Iron",
        .cs            = CI_CRAFT_SMELTER,
        .items[0].item = CI_IRON,
        .items[0].qty  = 1,
        .items[1].item = CI_COAL,
        .items[1].qty  = 1,
        .result        = CI_IRON,
    },
    {
        .name          = "Pelts",
        .cs            = CI_CRAFT_TANNING_RACK,
        .items[0].item = CI_UNCURED_HIDE,
        .items[0].qty  = 1,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty  = 0,
        .result        = CI_HIDE,
    },
    {
        .name          = "Polished Blocks",
        .cs            = CI_CRAFT_CRYSTAL_POLISHER,
        .items[0].item = CI_CUT_ROCK,
        .items[0].qty  = 1,
        .items[1].item = CI_DIAMOND_POWDER,
        .items[1].qty  = 1,
        .result        = CI_POLISHED_ROCK,
    },
    {
        .name          = "Polished Crystals",
        .cs            = CI_CRAFT_CRYSTAL_POLISHER,
        .items[0].item = CI_CRYSTAL,
        .items[0].qty  = 1,
        .items[1].item = CI_DIAMOND_POWDER,
        .items[1].qty  = 1,
        .result        = CI_POLISHED_CRYSTAL,
    },
    {
        .name          = "Rope",
        .cs            = CI_CRAFT_WORKBENCH,
        .items[0].item = CI_VINE,
        .items[0].qty  = 2,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty  = 0,
        .result        = CI_ROPE,
    },
    {
        .name          = "Salt",
        .cs            = CI_CRAFT_SMASHER,
        .items[0].item = CI_ROCK_SALT,
        .items[0].qty  = 1,
        .items[1].item = CI_NO_ITEM,
        .items[1].qty  = 0,
        .result        = CI_SALT,
    },
};