//==============================================================================
// Include
//==============================================================================

#include "ci_itemData.h"
#include "macros.h"

//==============================================================================
// Consts
//==============================================================================

const ciItem_t ciItemData[] = {
    {
        .image  = CI_FLOOR_PIZZA_WSG,
        .type   = CI_BAD_FOOD,
        .loc    = CI_M_FOREST,
        .size   = CI_MED,
        .weight = 3,
        .value  = -10,
        .title  = "Floor Pizza",
        .desc   = "Pizza from the floor. Let's hope nobody stepped on it.",
    },
    {
        .image  = CI_FURRY_MILK_WSG,
        .type   = CI_BAD_FOOD,
        .loc    = CI_SWAMP,
        .size   = CI_SMALL,
        .weight = 1,
        .value  = -30,
        .title  = "Furry Milk",
        .desc   = "Please don't think about where it came from.",
    },
    {
        .image  = CI_ICBINB_WSG,
        .type   = CI_BAD_FOOD,
        .loc    = CI_JUNGLE,
        .size   = CI_SMALL,
        .weight = 2,
        .value  = -50,
        .title  = "I Can't Believe It's Not Margarine!",
        .desc   = "It appears to be all natural butterfly.",
    },
    {
        .image  = CI_MALORT_WSG,
        .type   = CI_BAD_FOOD,
        .loc    = CI_MOUNTAIN,
        .size   = CI_MED,
        .weight = 7,
        .value  = -50,
        .title  = "Malort",
        .desc   = "There are things that taste worse, but not by much.",
    },
    {
        .image  = CI_PILK_WSG,
        .type   = CI_BAD_FOOD,
        .loc    = CI_SWAMP,
        .size   = CI_MED,
        .weight = 4,
        .value  = -30,
        .title  = "Pilk",
        .desc   = "On one hand, it's disgusting. On the other hand, PILK!",
    },
    {
        .image  = CI_RAVER_SWEAT_WSG,
        .type   = CI_BAD_FOOD,
        .loc    = CI_MOUNTAIN,
        .size   = CI_SMALL,
        .weight = 1,
        .value  = -20,
        .title  = "Raver Sweat",
        .desc   = "Ethically sourced, but may contain psychoactive chemicals.",
    },
    {
        .image  = CI_SQUIRREL_NUTS_WSG,
        .type   = CI_BAD_FOOD,
        .loc    = CI_JUNGLE,
        .size   = CI_SMALL,
        .weight = 1,
        .value  = -10,
        .title  = "Squirrel Nuts",
        .desc   = "Think one those cosplayers dropped these?",
    },
    {
        .image  = CI_YPLA_WSG,
        .type   = CI_BAD_FOOD,
        .loc    = CI_M_FOREST,
        .size   = CI_SMALL,
        .weight = 10,
        .value  = -1,
        .title  = "Your Parent's Lingering Affection",
        .desc   = "'Of course we love you, honey, but maybe if you'd settle down-'",
    },
    {
        .image  = CI_CLOTH_WSG,
        .type   = CI_CRAFTED,
        .loc    = CI_NONE,
        .size   = CI_MED,
        .weight = 5,
        .value  = 2,
        .title  = "Cloth",
        .desc   = "A small bit of cloth",
    },
    {
        .image  = CI_CUT_ROCK_WSG,
        .type   = CI_CRAFTED,
        .loc    = CI_NONE,
        .size   = CI_MED,
        .weight = 3,
        .value  = 0,
        .title  = "Cut Blocks",
        .desc   = "Much easier to build with",
    },
    {
        .image  = CI_DIAMOND_WSG,
        .type   = CI_CRAFTED,
        .loc    = CI_NONE,
        .size   = CI_SMALL,
        .weight = 1,
        .value  = 0,
        .title  = "Diamond",
        .desc   = "Ooooo. Shiny.",
    },
    {
        .image  = CI_DIAMOND_POWDER_WSG,
        .type   = CI_CRAFTED,
        .loc    = CI_NONE,
        .size   = CI_SMALL,
        .weight = 1,
        .value  = 0,
        .title  = "Diamond Powder",
        .desc   = "Try not to inhale it",
    },
    {
        .image  = CI_GEAR_WSG,
        .type   = CI_CRAFTED,
        .loc    = CI_NONE,
        .size   = CI_MED,
        .weight = 3,
        .value  = 2,
        .title  = "Gears",
        .desc   = "Useful for all manner of mechanical contraptions",
    },
    {
        .image  = CI_IRON_WSG,
        .type   = CI_CRAFTED,
        .loc    = CI_NONE,
        .size   = CI_MED,
        .weight = 7,
        .value  = 0,
        .title  = "Iron",
        .desc   = "Iron ready to use",
    },
    {
        .image  = CI_HIDE_WSG,
        .type   = CI_CRAFTED,
        .loc    = CI_NONE,
        .size   = CI_LARGE,
        .weight = 4,
        .value  = 0,
        .title  = "Pelts",
        .desc   = "Yeah, this is definitely pleather",
    },
    {
        .image  = CI_POLISHED_ROCK_WSG,
        .type   = CI_CRAFTED,
        .loc    = CI_NONE,
        .size   = CI_MED,
        .weight = 6,
        .value  = 0,
        .title  = "Polished Blocks",
        .desc   = "Perfect for a countertop",
    },
    {
        .image  = CI_POLISHED_CRYSTAL_WSG,
        .type   = CI_CRAFTED,
        .loc    = CI_NONE,
        .size   = CI_MED,
        .weight = 4,
        .value  = 0,
        .title  = "Polished Crystals",
        .desc   = "You can feel a buzz of mysterious energy flowing through it",
    },
    {
        .image  = CI_ROPE_WSG,
        .type   = CI_CRAFTED,
        .loc    = CI_NONE,
        .size   = CI_LARGE,
        .weight = 5,
        .value  = 1,
        .title  = "Rope",
        .desc   = "I can't believe you didn't start with at least 50ft of rope",
    },
    {
        .image  = CI_SALT_WSG,
        .type   = CI_CRAFTED,
        .loc    = CI_NONE,
        .size   = CI_SMALL,
        .weight = 1,
        .value  = 0,
        .title  = "Salt",
        .desc   = "Na: Explosive. Cl: Highly Acidic. NaCl: Tasty!",
    },
    {
        .image  = CI_STRING_WSG,
        .type   = CI_CRAFTED,
        .loc    = CI_NONE,
        .size   = CI_SMALL,
        .weight = 1,
        .value  = 1,
        .title  = "String",
        .desc   = "If you could dye it red, you might find someone important",
    },
    {
        .image  = CI_APPLE_WSG,
        .type   = CI_FOOD,
        .loc    = CI_FOREST,
        .size   = CI_SMALL,
        .weight = 1,
        .value  = 5,
        .title  = "Apple",
        .desc   = "It looks kinda... smooshed, but it should still taste good",
    },
    {
        .image  = CI_BEANS_WSG,
        .type   = CI_FOOD,
        .loc    = CI_M_FOREST,
        .size   = CI_SMALL,
        .weight = 4,
        .value  = 100,
        .title  = "Beans",
        .desc   = "I sure hope you brought a can opener",
    },
    {
        .image  = CI_BERRIES_WSG,
        .type   = CI_FOOD,
        .loc    = CI_FOREST,
        .size   = CI_SMALL,
        .weight = 1,
        .value  = 5,
        .title  = "Berries",
        .desc   = "A rich assortment of hopefully non-toxic berries",
    },
    {
        .image  = CI_DONUT_WSG,
        .type   = CI_FOOD,
        .loc    = CI_SWAMP,
        .size   = CI_SMALL,
        .weight = 2,
        .value  = 10,
        .title  = "Donuts",
        .desc   = "Donuts are classically a fall fruit, but occasionally you can find them out of season",
    },
    {
        .image  = CI_ENERGY_DRINK_WSG,
        .type   = CI_FOOD,
        .loc    = CI_SWAMP,
        .size   = CI_SMALL,
        .weight = 4,
        .value  = 30,
        .title  = "Energy Drink",
        .desc   = "Monster Bang Bull: Unleash your Winged Destiny!",
    },
    {
        .image  = CI_HONEY_WSG,
        .type   = CI_FOOD,
        .loc    = CI_FOREST,
        .size   = CI_SMALL,
        .weight = 3,
        .value  = 30,
        .title  = "Honey",
        .desc   = "Honey? Where is my superfood?",
    },
    {
        .image  = CI_MRE_WSG,
        .type   = CI_FOOD,
        .loc    = CI_MOUNTAIN,
        .size   = CI_MED,
        .weight = 6,
        .value  = 50,
        .title  = "MRE",
        .desc   = "Meal, Ready-to-Eat. Hopefully not the vegetable omelet meal",
    },
    {
        .image  = CI_MUSHROOMS_WSG,
        .type   = CI_FOOD,
        .loc    = CI_JUNGLE,
        .size   = CI_SMALL,
        .weight = 2,
        .value  = 20,
        .title  = "Mushrooms",
        .desc   = "Anything is edible at least once",
    },
    {
        .image  = CI_MYSTERY_MEAT_WSG,
        .type   = CI_FOOD,
        .loc    = CI_JUNGLE,
        .size   = CI_MED,
        .weight = 8,
        .value  = 30,
        .title  = "Mystery Meat",
        .desc   = "It was just lying there on the ground. Are you sure you want to eat it?",
    },
    {
        .image  = CI_PAN_PIZZA_WSG,
        .type   = CI_FOOD,
        .loc    = CI_MOUNTAIN,
        .size   = CI_SMALL,
        .weight = 2,
        .value  = 30,
        .title  = "Pan Pizza",
        .desc   = "Hot, fresh and ready. Nobody knows who made it",
    },
    {
        .image  = CI_PICKLES_WSG,
        .type   = CI_FOOD,
        .loc    = CI_JUNGLE,
        .size   = CI_SMALL,
        .weight = 5,
        .value  = 30,
        .title  = "Pickles",
        .desc   = "The pickles are reasonable, but where did the jar come from?",
    },
    {
        .image  = CI_PROTEIN_POWDER_WSG,
        .type   = CI_FOOD,
        .loc    = CI_M_FOREST,
        .size   = CI_MED,
        .weight = 6,
        .value  = 10,
        .title  = "Protein Powder",
        .desc   = "GOTTA GO TO THE GYM BRAH. GOTTA GET THEM GAINS BRAH.",
    },
    {
        .image  = CI_PUDDING_WSG,
        .type   = CI_FOOD,
        .loc    = CI_M_FOREST,
        .size   = CI_SMALL,
        .weight = 3,
        .value  = 60,
        .title  = "Pudding",
        .desc   = "Delicious pudding, good thing you have a spoon",
    },
    {
        .image  = CI_ROAST_TURKEY_WSG,
        .type   = CI_FOOD,
        .loc    = CI_MOUNTAIN,
        .size   = CI_MED,
        .weight = 10,
        .value  = 40,
        .title  = "Roast Turkey",
        .desc   = "There aren't even turkeys in the mountains...",
    },
    {
        .image  = CI_SQUEEZY_PEANUT_BUTTER_WSG,
        .type   = CI_FOOD,
        .loc    = CI_JUNGLE,
        .size   = CI_SMALL,
        .weight = 1,
        .value  = 5,
        .title  = "Squeezy Peanut Butter",
        .desc   = "Now you just need some jelly and two slices of bread",
    },
    {
        .image  = CI_STRING_CHEESE_WSG,
        .type   = CI_FOOD,
        .loc    = CI_SWAMP,
        .size   = CI_SMALL,
        .weight = 1,
        .value  = 20,
        .title  = "String Cheese",
        .desc   = "Best consumed between the hours of 3 and 4 AM next to a fountain",
    },
    {
        .image  = CI_TASTEFUL_NOODZ_WSG,
        .type   = CI_FOOD,
        .loc    = CI_SWAMP,
        .size   = CI_MED,
        .weight = 3,
        .value  = 35,
        .title  = "Tasty Noods",
        .desc   = "This wasn't what you expected, but it's still a nice find",
    },
    {
        .image  = CI_BAMBOO_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_JUNGLE,
        .size   = CI_MED,
        .weight = 3,
        .value  = 1,
        .title  = "Bamboo",
        .desc   = "All fall before the might of the bamboo pole",
    },
    {
        .image  = CI_HONEY_COMB_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_FOREST,
        .size   = CI_MED,
        .weight = 5,
        .value  = 0,
        .title  = "Beehive",
        .desc   = "Did you know, according to all known laws of physics-",
    },
    {
        .image  = CI_BIRCH_BARK_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_SWAMP,
        .size   = CI_SMALL,
        .weight = 2,
        .value  = 10,
        .title  = "Birch Bark",
        .desc   = "A thin bark that's got a variety of uses",
    },
    {
        .image  = CI_COAL_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_MOUNTAIN,
        .size   = CI_MED,
        .weight = 8,
        .value  = 50,
        .title  = "Coal",
        .desc   = "Maybe if you're bad, a secular icon will sneak into your house and give you more",
    },
    {
        .image  = CI_CRYSTAL_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_M_FOREST,
        .size   = CI_SMALL,
        .weight = 3,
        .value  = 255,
        .title  = "Crystal",
        .desc   = "If only it wasn't so rough it would be extremely pretty",
    },
    {
        .image  = CI_DRIED_GRASS_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_FOREST,
        .size   = CI_SMALL,
        .weight = 1,
        .value  = 2,
        .title  = "Dried Grasses",
        .desc   = "Extremely flammable, but very useful",
    },
    {
        .image  = CI_IRON_ORE_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_MOUNTAIN,
        .size   = CI_MED,
        .weight = 10,
        .value  = 0,
        .title  = "Iron Ore",
        .desc   = "Raw iron clawed straight from the earth",
    },
    {
        .image  = CI_LARGE_LEAF_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_JUNGLE,
        .size   = CI_MED,
        .weight = 5,
        .value  = 2,
        .title  = "Large Leaves",
        .desc   = "Any bigger and you could use it a parachute",
    },
    {
        .image  = CI_LATEX_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_FOREST,
        .size   = CI_SMALL,
        .weight = 2,
        .value  = 0,
        .title  = "Latex",
        .desc   = "Latex comes from a rubber tree. It's not the weirdest thing to find out here",
    },
    {
        .image  = CI_LOG_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_FOREST,
        .size   = CI_LARGE,
        .weight = 20,
        .value  = 50,
        .title  = "Logs",
        .desc   = "Make sure to send this along with your bug report",
    },
    {
        .image  = CI_RESIN_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_JUNGLE,
        .size   = CI_SMALL,
        .weight = 2,
        .value  = 0,
        .title  = "Resin",
        .desc   = "Everything is now sticky. Fingers. Clothes. The tree. Your pockets.",
    },
    {
        .image  = CI_ROCKS_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_ALL,
        .size   = CI_MED,
        .weight = 8,
        .value  = 0,
        .title  = "Rocks",
        .desc   = "Sure, there's lots of rocks around but these ones are special!",
    },
    {
        .image  = CI_ROCK_SALT_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_MOUNTAIN,
        .size   = CI_MED,
        .weight = 4,
        .value  = 0,
        .title  = "Rock Salt",
        .desc   = "If you heat this up, exactly nothing magical will happen",
    },
    {
        .image  = CI_SPIDER_WEB_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_SWAMP,
        .size   = CI_SMALL,
        .weight = 1,
        .value  = 0,
        .title  = "Spiderweb",
        .desc   = "Sorry I'm not at home right now. Leave a message and I'll call you back",
    },
    {
        .image  = CI_STICK_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_ALL,
        .size   = CI_SMALL,
        .weight = 2,
        .value  = 5,
        .title  = "Sticks",
        .desc   = "If you break your bones, getting out of here is going to suck",
    },
    {
        .image  = CI_UNCURED_HIDE_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_SWAMP,
        .size   = CI_LARGE,
        .weight = 7,
        .value  = 0,
        .title  = "Uncured Hides",
        .desc   = "This was just lying there on the floor... wait, isn't this pleather?",
    },
    {
        .image  = CI_VINE_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_JUNGLE,
        .size   = CI_MED,
        .weight = 5,
        .value  = 0,
        .title  = "Vines",
        .desc   = "Make sure to yell while you swing",
    },
    {
        .image  = CI_TAR_WSG,
        .type   = CI_FORAGED,
        .loc    = CI_SWAMP,
        .size   = CI_MED,
        .weight = 5,
        .value  = 20,
        .title  = "Tar",
        .desc   = "Try not to sink",
    },
    {
        .image  = CI_HEALING_POWDER_WSG,
        .type   = CI_HEALING,
        .loc    = CI_NONE,
        .size   = CI_SMALL,
        .weight = 2,
        .value  = 30,
        .title  = "Healing Powder",
        .desc   = "Usage instructions: Inhale deeply and ignore the pretty lights",
    },
    {
        .image  = CI_BANDAGES_WSG,
        .type   = CI_HEALING,
        .loc    = CI_NONE,
        .size   = CI_SMALL,
        .weight = 1,
        .value  = 50,
        .title  = "Bandages",
        .desc   = "If you get enough of these, you can pretend to be a mummy",
    },
    {
        .image  = CI_POULTICE_WSG,
        .type   = CI_HEALING,
        .loc    = CI_NONE,
        .size   = CI_SMALL,
        .weight = 3,
        .value  = 35,
        .title  = "Healing Poultice",
        .desc   = "Looking at the ingredient list, it's a surprise this heals you up",
    },
    {
        .image  = CI_HEALING_POTION_WSG,
        .type   = CI_HEALING,
        .loc    = CI_NONE,
        .size   = CI_SMALL,
        .weight = 5,
        .value  = 100,
        .title  = "Potion",
        .desc   = "It's not... glowing, is it?",
    },
    {
        .image  = CI_HEART_WSG,
        .type   = CI_HEALING,
        .loc    = CI_NONE,
        .size   = CI_SMALL,
        .weight = 0,
        .value  = 75,
        .title  = "Healing Heart",
        .desc   = "Legend says these could be ripped out of monsters once upon a time",
    },
};

//==============================================================================
// Functions
//==============================================================================

int ciGetArrayLength()
{
    return ARRAY_SIZE(ciItemData);
}