#ifndef SOKO_CONSTS_H
#define SOKO_CONSTS_H

#define SOKO_LEVEL_COUNT 4
#define SOKO_MAX_LEVELSIZE 30
#define SOKO_MAX_ENTITY_COUNT 15
#define SOKO_MAX_PORTALS 10
#define SOKO_VICTORY_TIMER_US 1000000

#endif //SOKO_CONSTS_H